#pragma once

#define NOZZLE_CLEAN_FEATURE

#ifndef NOZZLE_CLEAN_STROKES
    #define NOZZLE_CLEAN_STROKES  12
#endif

#ifndef NOZZLE_CLEAN_TRIANGLES
    #define NOZZLE_CLEAN_TRIANGLES  3
#endif

#ifndef NOZZLE_CLEAN_START_POINT
    #define NOZZLE_CLEAN_START_POINT { {  30, 30, (Z_MIN_POS + 1) } }
#endif

#ifndef NOZZLE_CLEAN_END_POINT
    #define NOZZLE_CLEAN_END_POINT { { 100, 60, (Z_MIN_POS + 1) } }
#endif

#ifndef NOZZLE_CLEAN_CIRCLE_RADIUS
    #define NOZZLE_CLEAN_CIRCLE_RADIUS 6.5
#endif

#ifndef NOZZLE_CLEAN_CIRCLE_FN
    #define NOZZLE_CLEAN_CIRCLE_FN 10
#endif

#ifndef NOZZLE_CLEAN_CIRCLE_MIDDLE
    #define NOZZLE_CLEAN_CIRCLE_MIDDLE NOZZLE_CLEAN_START_POINT
#endif

#ifndef NOZZLE_CLEAN_GOBACK
    #define NOZZLE_CLEAN_GOBACK true
#endif

#ifndef NOZZLE_CLEAN_NO_Z
    #define NOZZLE_CLEAN_NO_Z fasle
#endif

#ifndef NOZZLE_CLEAN_NO_Y
    #define NOZZLE_CLEAN_NO_Y false
#endif

#ifndef NOZZLE_CLEAN_ENABLE_WIPE_SEQUENCE_COMMANDS
    #define NOZZLE_CLEAN_COMMANDS false
#endif

#ifndef NOZZLE_CLEAN_WIPE_SEQUENCE_COMMANDS
    #define NOZZLE_CLEAN_WIPE_SEQUENCE_COMMANDS "G1 X-17 Y25 Z10 F4000\nG1 Z1\nM114\nG1 X-17 Y25\nG1 X-17 Y95\nG1 X-17 Y25\nG1 X-17 Y95\nG1 X-17 Y25\nG1 X-17 Y95\nG1 X-17 Y25\nG1 X-17 Y95\nG1 X-17 Y25\nG1 X-17 Y95\nG1 X-17 Y25\nG1 X-17 Y95\nG1 Z15\nM400\nG0 X-10.0 Y-9.0"
#endif