#pragma once

#define EXTRUDER_GEAR_RATIO         GEAR_RATIO_3_1
#define EXTRUDER_GEAR_DIAMETER      7.3
#define STEPS_MM_EXTRUDER           (MOTOR_E_FULL_STEPS * MOTOR_E_MICROSTEPS * EXTRUDER_GEAR_RATIO / (EXTRUDER_GEAR_DIAMETER * 3.142))