#pragma once
#include "../motions.h"

#define cartesian MOTION_CARTESIAN

#ifndef AXIS_X_ENDSTOP_MIN
    #define AXIS_X_ENDSTOP_MIN true
#endif

#ifndef AXIS_X_ENDSTOP_MAX
    #define AXIS_X_ENDSTOP_MAX false
#endif

#ifndef AXIS_Y_ENDSTOP_MIN
    #define AXIS_Y_ENDSTOP_MIN true
#endif

#ifndef AXIS_Y_ENDSTOP_MAX
    #define AXIS_Y_ENDSTOP_MAX false
#endif

#ifndef AXIS_Z_ENDSTOP_MIN
    #define AXIS_Z_ENDSTOP_MIN true
#endif

#ifndef AXIS_Z_ENDSTOP_MAX
    #define AXIS_Z_ENDSTOP_MAX false
#endif

//
#ifndef AXIS_X_ENDSTOP_MIN_PULLUP
    #define AXIS_X_ENDSTOP_MIN_PULLUP false
#endif

#ifndef AXIS_X_ENDSTOP_MAX_PULLUP
    #define AXIS_X_ENDSTOP_MAX_PULLUP false
#endif

#ifndef AXIS_Y_ENDSTOP_MIN_PULLUP
    #define AXIS_Y_ENDSTOP_MIN_PULLUP false
#endif

#ifndef AXIS_Y_ENDSTOP_MAX_PULLUP
    #define AXIS_Y_ENDSTOP_MAX_PULLUP false
#endif

#ifndef AXIS_Z_ENDSTOP_MIN_PULLUP
    #define AXIS_Z_ENDSTOP_MIN_PULLUP false
#endif

#ifndef AXIS_Z_ENDSTOP_MAX_PULLUP
    #define AXIS_Z_ENDSTOP_MAX_PULLUP false
#endif

#ifndef AXIS_Z_ENDSTOP_MIN_PROBE_PULLUP
    #define AXIS_Z_ENDSTOP_MIN_PROBE_PULLUP false
#endif

//
#ifndef AXIS_X_ENDSTOP_MIN_PULLDOWN
    #define AXIS_X_ENDSTOP_MIN_PULLDOWN false
#endif

#ifndef AXIS_X_ENDSTOP_MAX_PULLDOWN
    #define AXIS_X_ENDSTOP_MAX_PULLDOWN false
#endif

#ifndef AXIS_Y_ENDSTOP_MIN_PULLDOWN
    #define AXIS_Y_ENDSTOP_MIN_PULLDOWN false
#endif

#ifndef AXIS_Y_ENDSTOP_MAX_PULLDOWN
    #define AXIS_Y_ENDSTOP_MAX_PULLDOWN false
#endif

#ifndef AXIS_Z_ENDSTOP_MIN_PULLDOWN
    #define AXIS_Z_ENDSTOP_MIN_PULLDOWN false
#endif

#ifndef AXIS_Z_ENDSTOP_MAX_PULLDOWN
    #define AXIS_Z_ENDSTOP_MAX_PULLDOWN false
#endif

#ifndef AXIS_Z_ENDSTOP_MIN_PROBE_PULLDOWN
    #define AXIS_Z_ENDSTOP_MIN_PROBE_PULLDOWN false
#endif
//

#ifndef AXIS_X_ENDSTOP_MIN_INVERTING
    #define AXIS_X_ENDSTOP_MIN_INVERTING false
#endif

#ifndef AXIS_X_ENDSTOP_MAX_INVERTING 
    #define AXIS_X_ENDSTOP_MAX_INVERTING false
#endif

#ifndef AXIS_Y_ENDSTOP_MIN_INVERTING 
    #define AXIS_Y_ENDSTOP_MIN_INVERTING false
#endif

#ifndef AXIS_Y_ENDSTOP_MAX_INVERTING 
    #define AXIS_Y_ENDSTOP_MAX_INVERTING false
#endif

#ifndef AXIS_Z_ENDSTOP_MIN_INVERTING 
    #define AXIS_Z_ENDSTOP_MIN_INVERTING false
#endif
#ifndef AXIS_Z_ENDSTOP_MAX_INVERTING 
    #define AXIS_Z_ENDSTOP_MAX_INVERTING false
#endif

#ifndef AXIS_Z_ENDSTOP_MIN_PROBE_INVERTING 
    #define AXIS_Z_ENDSTOP_MIN_PROBE_INVERTING false
#endif
//

#ifndef AXIS_X_DRIVER
    #define AXIS_X_DRIVER A4988
#endif

#ifndef AXIS_Y_DRIVER
    #define AXIS_Y_DRIVER A4988
#endif

#ifndef AXIS_Z_DRIVER
    #define AXIS_Z_DRIVER A4988
#endif

#ifndef AXIS_X2_DRIVER
    #define AXIS_X2_DRIVER A4988
#endif

#ifndef AXIS_Y2_DRIVER
    #define AXIS_Y2_DRIVER A4988
#endif

#ifndef AXIS_Z2_DRIVER
    #define AXIS_Z2_DRIVER A4988
#endif

#ifndef AXIS_Z3_DRIVER
    #define AXIS_Z3_DRIVER A4988
#endif

#ifndef AXIS_Z4_DRIVER
    #define AXIS_Z4_DRIVER A4988
#endif

#ifndef AXIS_E0_DRIVER
    #define AXIS_E0_DRIVER A4988
#endif

#ifndef AXIS_E1_DRIVER
    #define AXIS_E1_DRIVER A4988
#endif

#ifndef AXIS_E2_DRIVER
    #define AXIS_E2_DRIVER A4988
#endif

#ifndef AXIS_E3_DRIVER
    #define AXIS_E3_DRIVER A4988
#endif

#ifndef AXIS_E4_DRIVER
    #define AXIS_E4_DRIVER A4988
#endif

#ifndef AXIS_E5_DRIVER
    #define AXIS_E5_DRIVER A4988
#endif

#ifndef AXIS_E6_DRIVER
    #define AXIS_E6_DRIVER A4988
#endif

#ifndef AXIS_E7_DRIVER
    #define AXIS_E7_DRIVER A4988
#endif
//

#ifndef AXIS_X_STEPS_MM
    #define AXIS_X_STEPS_MM 80
#endif

#ifndef AXIS_Y_STEPS_MM 
    #define AXIS_Y_STEPS_MM 80
#endif

#ifndef AXIS_Z_STEPS_MM
    #define AXIS_Z_STEPS_MM 4000
#endif

#ifndef AXIS_E0_STEPS_MM
    #define AXIS_E0_STEPS_MM 500
#endif

#ifndef AXIS_E1_STEPS_MM
    #define AXIS_E1_STEPS_MM AXIS_E0_STEPS_MM
#endif

#ifndef AXIS_E2_STEPS_MM
    #define AXIS_E2_STEPS_MM AXIS_E0_STEPS_MM
#endif

#ifndef AXIS_E3_STEPS_MM
    #define AXIS_E3_STEPS_MM AXIS_E0_STEPS_MM
#endif

#ifndef AXIS_E4_STEPS_MM
    #define AXIS_E4_STEPS_MM AXIS_E0_STEPS_MM
#endif

#ifndef AXIS_E5_STEPS_MM
    #define AXIS_E5_STEPS_MM AXIS_E0_STEPS_MM
#endif

#ifndef AXIS_E6_STEPS_MM
    #define AXIS_E6_STEPS_MM AXIS_E0_STEPS_MM
#endif

#ifndef AXIS_E7_STEPS_MM
    #define AXIS_E7_STEPS_MM AXIS_E0_STEPS_MM
#endif
//

#ifndef AXIS_X_MAX_FEEDRATE
    #define AXIS_X_MAX_FEEDRATE 300
#endif

#ifndef AXIS_Y_MAX_FEEDRATE 
    #define AXIS_Y_MAX_FEEDRATE 300
#endif

#ifndef AXIS_Z_MAX_FEEDRATE
    #define AXIS_Z_MAX_FEEDRATE 5
#endif

#ifndef AXIS_E0_MAX_FEEDRATE
    #define AXIS_E0_MAX_FEEDRATE 25
#endif

#ifndef AXIS_E1_MAX_FEEDRATE
    #define AXIS_E1_MAX_FEEDRATE AXIS_E0_MAX_FEEDRATE
#endif

#ifndef AXIS_E2_MAX_FEEDRATE
    #define AXIS_E2_MAX_FEEDRATE AXIS_E0_MAX_FEEDRATE
#endif

#ifndef AXIS_E3_MAX_FEEDRATE
    #define AXIS_E3_MAX_FEEDRATE AXIS_E0_MAX_FEEDRATE
#endif

#ifndef AXIS_E4_MAX_FEEDRATE
    #define AXIS_E4_MAX_FEEDRATE AXIS_E0_MAX_FEEDRATE
#endif

#ifndef AXIS_E5_MAX_FEEDRATE
    #define AXIS_E5_MAX_FEEDRATE AXIS_E0_MAX_FEEDRATE
#endif

#ifndef AXIS_E6_MAX_FEEDRATE
    #define AXIS_E6_MAX_FEEDRATE AXIS_E0_MAX_FEEDRATE
#endif

#ifndef AXIS_E7_MAX_FEEDRATE
    #define AXIS_E7_MAX_FEEDRATE AXIS_E0_MAX_FEEDRATE
#endif
//

#ifndef AXIS_X_MAX_FEEDRATE_EDIT_VALUE
    #define AXIS_X_MAX_FEEDRATE_EDIT_VALUE 600
#endif

#ifndef AXIS_Y_MAX_FEEDRATE_EDIT_VALUE 
    #define AXIS_Y_MAX_FEEDRATE_EDIT_VALUE 600
#endif

#ifndef AXIS_Z_MAX_FEEDRATE_EDIT_VALUE
    #define AXIS_Z_MAX_FEEDRATE_EDIT_VALUE 10
#endif

#ifndef AXIS_E0_MAX_FEEDRATE_EDIT_VALUE
    #define AXIS_E0_MAX_FEEDRATE_EDIT_VALUE 50
#endif

#ifndef AXIS_E1_MAX_FEEDRATE_EDIT_VALUE
    #define AXIS_E1_MAX_FEEDRATE_EDIT_VALUE AXIS_E0_MAX_FEEDRATE_EDIT_VALUE
#endif

#ifndef AXIS_E2_MAX_FEEDRATE_EDIT_VALUE
    #define AXIS_E2_MAX_FEEDRATE_EDIT_VALUE AXIS_E0_MAX_FEEDRATE_EDIT_VALUE
#endif

#ifndef AXIS_E3_MAX_FEEDRATE_EDIT_VALUE
    #define AXIS_E3_MAX_FEEDRATE_EDIT_VALUE AXIS_E0_MAX_FEEDRATE_EDIT_VALUE
#endif

#ifndef AXIS_E4_MAX_FEEDRATE_EDIT_VALUE
    #define AXIS_E4_MAX_FEEDRATE_EDIT_VALUE AXIS_E0_MAX_FEEDRATE_EDIT_VALUE
#endif

#ifndef AXIS_E5_MAX_FEEDRATE_EDIT_VALUE
    #define AXIS_E5_MAX_FEEDRATE_EDIT_VALUE AXIS_E0_MAX_FEEDRATE_EDIT_VALUE
#endif

#ifndef AXIS_E6_MAX_FEEDRATE_EDIT_VALUE
    #define AXIS_E6_MAX_FEEDRATE_EDIT_VALUE AXIS_E0_MAX_FEEDRATE_EDIT_VALUE
#endif

#ifndef AXIS_E7_MAX_FEEDRATE_EDIT_VALUE
    #define AXIS_E7_MAX_FEEDRATE_EDIT_VALUE AXIS_E0_MAX_FEEDRATE_EDIT_VALUE
#endif
//

#ifndef AXIS_X_MAX_ACCELERATION
    #define AXIS_X_MAX_ACCELERATION 3000
#endif

#ifndef AXIS_Y_MAX_ACCELERATION 
    #define AXIS_Y_MAX_ACCELERATION 3000
#endif

#ifndef AXIS_Z_MAX_ACCELERATION
    #define AXIS_Z_MAX_ACCELERATION 100
#endif

#ifndef AXIS_E0_MAX_ACCELERATION
    #define AXIS_E0_MAX_ACCELERATION 10000
#endif

#ifndef AXIS_E1_MAX_ACCELERATION
    #define AXIS_E1_MAX_ACCELERATION AXIS_E0_MAX_ACCELERATION
#endif

#ifndef AXIS_E2_MAX_ACCELERATION
    #define AXIS_E2_MAX_ACCELERATION AXIS_E0_MAX_ACCELERATION
#endif

#ifndef AXIS_E3_MAX_ACCELERATION
    #define AXIS_E3_MAX_ACCELERATION AXIS_E0_MAX_ACCELERATION
#endif

#ifndef AXIS_E4_MAX_ACCELERATION
    #define AXIS_E4_MAX_ACCELERATION AXIS_E0_MAX_ACCELERATION
#endif

#ifndef AXIS_E5_MAX_ACCELERATION
    #define AXIS_E5_MAX_ACCELERATION AXIS_E0_MAX_ACCELERATION
#endif

#ifndef AXIS_E6_MAX_ACCELERATION
    #define AXIS_E6_MAX_ACCELERATION AXIS_E0_MAX_ACCELERATION
#endif

#ifndef AXIS_E7_MAX_ACCELERATION
    #define AXIS_E7_MAX_ACCELERATION AXIS_E0_MAX_ACCELERATION
#endif
//

#ifndef AXIS_X_MAX_ACCELERATION_EDIT_VALUE
    #define AXIS_X_MAX_ACCELERATION_EDIT_VALUE 6000
#endif

#ifndef AXIS_Y_MAX_ACCELERATION_EDIT_VALUE 
    #define AXIS_Y_MAX_ACCELERATION_EDIT_VALUE 6000
#endif

#ifndef AXIS_Z_MAX_ACCELERATION_EDIT_VALUE
    #define AXIS_Z_MAX_ACCELERATION_EDIT_VALUE 200
#endif

#ifndef AXIS_E0_MAX_ACCELERATION_EDIT_VALUE
    #define AXIS_E0_MAX_ACCELERATION_EDIT_VALUE 20000
#endif

#ifndef AXIS_E1_MAX_ACCELERATION_EDIT_VALUE
    #define AXIS_E1_MAX_ACCELERATION_EDIT_VALUE AXIS_E0_MAX_ACCELERATION_EDIT_VALUE
#endif

#ifndef AXIS_E2_MAX_ACCELERATION_EDIT_VALUE
    #define AXIS_E2_MAX_ACCELERATION_EDIT_VALUE AXIS_E0_MAX_ACCELERATION_EDIT_VALUE
#endif

#ifndef AXIS_E3_MAX_ACCELERATION_EDIT_VALUE
    #define AXIS_E3_MAX_ACCELERATION_EDIT_VALUE AXIS_E0_MAX_ACCELERATION_EDIT_VALUE
#endif

#ifndef AXIS_E4_MAX_ACCELERATION_EDIT_VALUE
    #define AXIS_E4_MAX_ACCELERATION_EDIT_VALUE AXIS_E0_MAX_ACCELERATION_EDIT_VALUE
#endif

#ifndef AXIS_E5_MAX_ACCELERATION_EDIT_VALUE
    #define AXIS_E5_MAX_ACCELERATION_EDIT_VALUE AXIS_E0_MAX_ACCELERATION_EDIT_VALUE
#endif

#ifndef AXIS_E6_MAX_ACCELERATION_EDIT_VALUE
    #define AXIS_E6_MAX_ACCELERATION_EDIT_VALUE AXIS_E0_MAX_ACCELERATION_EDIT_VALUE
#endif

#ifndef AXIS_E7_MAX_ACCELERATION_EDIT_VALUE
    #define AXIS_E7_MAX_ACCELERATION_EDIT_VALUE AXIS_E0_MAX_ACCELERATION_EDIT_VALUE
#endif


