#pragma once

#ifndef EXTRUDER_NUMBERS
    #define EXTRUDER_NUMBERS 1
#endif

#ifndef EXTRUDER_FILAMENT_DIAMETER 
    #define EXTRUDER_FILAMENT_DIAMETER  1.75
#endif

#ifndef EXTRUDER_SINGLENOZZLE
    #define EXTRUDER_SINGLENOZZLE false
#endif

#ifndef EXTRUDER_SINGLENOZZLE_STANDBY_TEMP
    #define EXTRUDER_SINGLENOZZLE_STANDBY_TEMP false
#endif

#ifndef EXTRUDER_SINGLENOZZLE_STANDBY_FAN
    #define EXTRUDER_SINGLENOZZLE_STANDBY_FAN false
#endif

#ifndef EXTRUDER_SWITCHING
    #define EXTRUDER_SWITCHING false
#endif

#ifndef EXTRUDER_SWITCHING_SERVO_NR
    #define EXTRUDER_SWITCHING_SERVO_NR 0
#endif

#ifndef EXTRUDER_SWITCHING_SERVO_ANGLES
    #define EXTRUDER_SWITCHING_SERVO_ANGLES { 0, 90}
#endif

#ifndef EXTRUDER_SWITCHING_E23_SERVO_NR
    #define EXTRUDER_SWITCHING_E23_SERVO_NR 1
#endif

#ifndef EXTRUDER_SWITCHING_NOZZLE
    #define EXTRUDER_SWITCHING_NOZZLE false
#endif

#ifndef EXTRUDER_SWITCHING_NOZZLE_SERVO_NR
    #define EXTRUDER_SWITCHING_NOZZLE_SERVO_NR 0
#endif

#ifndef EXTRUDER_SWITCHING_NOZZLE_E1_SERVO_NR
    #define EXTRUDER_SWITCHING_NOZZLE_E1_SERVO_NR 1
#endif

#ifndef EXTRUDER_SWITCHING_NOZZLE_SERVO_ANGLES
    #define EXTRUDER_SWITCHING_NOZZLE_SERVO_ANGLES { 0, 90 }
#endif

#ifndef EXTRUDER_PARKING
    #define EXTRUDER_PARKING false
#endif

#ifndef EXTRUDER_PARKING_MAGNETIC
    #define EXTRUDER_PARKING_MAGNETIC false
#endif

#ifndef EXTRUDER_PARKING_X
    #define EXTRUDER_PARKING_X { -78, 184}
#endif

#ifndef EXTRUDER_PARKING_GRAB_DISTANCE
    #define EXTRUDER_PARKING_GRAB_DISTANCE 1
#endif

#ifndef EXTRUDER_PARKING_MANUAL_SOLENOID_CONTROL
    #define EXTRUDER_PARKING_MANUAL_SOLENOID_CONTROL false
#endif

#ifndef EXTRUDER_PARKING_SOLENOIDS_INVERT
    #define EXTRUDER_PARKING_SOLENOIDS_INVERT true
#endif

#ifndef EXTRUDER_PARKING_SOLENOIDS_PINS_ACTIVE
    #define EXTRUDER_PARKING_SOLENOIDS_PINS_ACTIVE LOW
#endif

#ifndef EXTRUDER_PARKING_SOLENOIDS_DELAY 
    #define EXTRUDER_PARKING_SOLENOIDS_DELAY 250
#endif

#ifndef EXTRUDER_PARKING_MAGNETIC_FAST_SPEED
    #define EXTRUDER_PARKING_MAGNETIC_FAST_SPEED 9000
#endif

#ifndef EXTRUDER_PARKING_MAGNETIC_SLOW_SPEED
    #define EXTRUDER_PARKING_MAGNETIC_SLOW_SPEED 4500
#endif

#ifndef EXTRUDER_PARKING_MAGNETIC_TRAVEL_DISTANCE
    #define EXTRUDER_PARKING_MAGNETIC_TRAVEL_DISTANCE 10
#endif

#ifndef EXTRUDER_PARKING_MAGNETIC_COMPENSATION
    #define EXTRUDER_PARKING_MAGNETIC_COMPENSATION 0
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD
    #define EXTRUDER_SWITCHING_TOOLHEAD false
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_MAGNETIC
    #define EXTRUDER_SWITCHING_TOOLHEAD_MAGNETIC false
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_ELECTROMAGNETIC
    #define EXTRUDER_SWITCHING_TOOLHEAD_ELECTROMAGNETIC false
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_Y_POS
    #define EXTRUDER_SWITCHING_TOOLHEAD_Y_POS 235
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_Y_SECURITY
    #define EXTRUDER_SWITCHING_TOOLHEAD_Y_SECURITY 10
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_Y_CLEAR
    #define EXTRUDER_SWITCHING_TOOLHEAD_Y_CLEAR 60
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_X_POS
    #define EXTRUDER_SWITCHING_TOOLHEAD_X_POS { 215, 0 }
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_SERVO_NR
    #define EXTRUDER_SWITCHING_TOOLHEAD_SERVO_NR 2
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_SERVO_ANGLES
    #define EXTRUDER_SWITCHING_TOOLHEAD_SERVO_ANGLES { 0, 180 }
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_Y_RELEASE
    #define EXTRUDER_SWITCHING_TOOLHEAD_Y_RELEASE 5
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_X_SECURITY
    #define EXTRUDER_SWITCHING_TOOLHEAD_X_SECURITY { 90, 150}
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_PRIME_BEFORE_REMOVE 
    #define EXTRUDER_SWITCHING_TOOLHEAD_PRIME_BEFORE_REMOVE true
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_PRIME_MM
    #define EXTRUDER_SWITCHING_TOOLHEAD_PRIME_MM 20
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_RETRACT_MM
    #define EXTRUDER_SWITCHING_TOOLHEAD_RETRACT_MM 10
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_PRIME_FEEDRATE
    #define EXTRUDER_SWITCHING_TOOLHEAD_PRIME_FEEDRATE 300
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_RETRACT_FEEDRATE
    #define EXTRUDER_SWITCHING_TOOLHEAD_RETRACT_FEEDRATE 2400
#endif

#ifndef EXTRUDER_SWITCHING_TOOLHEAD_Z_HOP
    #define EXTRUDER_SWITCHING_TOOLHEAD_Z_HOP 2
#endif

#ifndef EXTRUDER_MIXING
    #define EXTRUDER_MIXING false
#endif

#ifndef EXTRUDER_MIXING_STEPPERS
    #define EXTRUDER_MIXING_STEPPERS 2
#endif

#ifndef EXTRUDER_MIXING_VIRTUAL_TOOLS
    #define EXTRUDER_MIXING_VIRTUAL_TOOLS 16
#endif

#ifndef EXTRUDER_MIXING_DIRECT_IN_G1
    #define EXTRUDER_MIXING_DIRECT_IN_G1 false
#endif

#ifndef EXTRUDER_MIXING_GRADIENT
    #define EXTRUDER_MIXING_GRADIENT false
#endif

#ifndef EXTRUDER_MIXING_GRADIENT_VTOOL
    #define EXTRUDER_MIXING_GRADIENT_VTOOL false
#endif

#ifndef EXTRUDER_HOTEND_OFFSET_X
    #define EXTRUDER_HOTEND_OFFSET_X { 0.0, 20.00 }
#endif

#ifndef EXTRUDER_HOTEND_OFFSET_Y
    #define EXTRUDER_HOTEND_OFFSET_Y { 0.0, 5.00 }
#endif

#ifndef EXTRUDER_HOTEND_OFFSET_Z
    #define EXTRUDER_HOTEND_OFFSET_Z { 0.0, 0.00 }
#endif

/***********************************************************************/
// ┌──────────────────┐
// │ pre-sanity check │
// └──────────────────┘

#if ENABLED(EXTRUDER_SWITCHING_NOZZLE)
    #undef EXTRUDER_NUMBERS
    #define EXTRUDER_NUMBERS 2
#endif

/***********************************************************************/
// ┌──────────┐
// │ optional │
// └──────────┘

#undef EXTRUDER_SWITCHING_NOZZLE_E1_SERVO_NR
#undef EXTRUDER_HOTEND_OFFSET_X
#undef EXTRUDER_HOTEND_OFFSET_Y
#undef EXTRUDER_HOTEND_OFFSET_Z