#pragma once

#define MOTION_CARTESIAN        100

#define MOTION_COREXY           200
#define MOTION_COREXZ           201
#define MOTION_COREYZ           202
#define MOTION_COREYX           203
#define MOTION_COREZX           204
#define MOTION_COREZY           205
#define MOTION_MARKFORGED_XY    206

#define MOTION_DELTA            300 
#define MOTION_SCARA            400

#define MOTION_FORWARD          true
#define MOTION_BACKWARD         false
#define MOTION_CLOCKWISE        true
#define MOTION_COUNTERCLOCKWISE false

#ifndef MOTION_DISTINCT_E_FACTORS
    #define MOTION_DISTINCT_E_FACTORS false
#endif

#ifndef MOTION_LIMITED_MAX_FEEDRATE_EDITING
    #define MOTION_LIMITED_MAX_FEEDRATE_EDITING false
#endif

#ifndef MOTION_LIMITED_MAX_ACCELERATION_EDITING
    #define MOTION_LIMITED_MAX_ACCELERATION_EDITING false
#endif

#ifndef MOTION_DEFAULT_ACCELERATION
    #define MOTION_DEFAULT_ACCELERATION 3000
#endif

#ifndef MOTION_DEFAULT_RETRACT_ACCELERATION
    #define MOTION_DEFAULT_RETRACT_ACCELERATION 3000
#endif

#ifndef MOTION_DEFAULT_TRAVEL_ACCELERATION
    #define MOTION_DEFAULT_TRAVEL_ACCELERATION 3000
#endif