#pragma once

#define MOTION_CARTESIAN        100

#define MOTION_COREXY           200
#define MOTION_COREXZ           201
#define MOTION_COREYZ           202
#define MOTION_COREYX           203
#define MOTION_COREZX           204
#define MOTION_COREZY           205
#define MOTION_MARKFORGED_XY    206

#define MOTION_DELTA            300 
#define MOTION_SCARA            400

#define MOTION_FORWARD          true
#define MOTION_BACKWARD         false
#define MOTION_CLOCKWISE        true
#define MOTION_COUNTERCLOCKWISE false

#ifndef MOTION_DISTINCT_E_FACTORS
    #define MOTION_DISTINCT_E_FACTORS false
#endif

#ifndef MOTION_LIMITED_MAX_FEEDRATE_EDITING
    #define MOTION_LIMITED_MAX_FEEDRATE_EDITING false
#endif

#ifndef MOTION_LIMITED_MAX_ACCELERATION_EDITING
    #define MOTION_LIMITED_MAX_ACCELERATION_EDITING false
#endif

#ifndef MOTION_LIMITED_JERK_EDITING
    #define MOTION_LIMITED_JERK_EDITING false
#endif

#ifndef MOTION_DEFAULT_ACCELERATION
    #define MOTION_DEFAULT_ACCELERATION 3000
#endif

#ifndef MOTION_DEFAULT_RETRACT_ACCELERATION
    #define MOTION_DEFAULT_RETRACT_ACCELERATION 3000
#endif

#ifndef MOTION_DEFAULT_TRAVEL_ACCELERATION
    #define MOTION_DEFAULT_TRAVEL_ACCELERATION 3000
#endif

#ifndef MOTION_CLASSIC_JERK
    #define MOTION_CLASSIC_JERK false
#endif

#ifndef MOTION_TRAVEL_EXTRA_XYJERK
    #define MOTION_TRAVEL_EXTRA_XYJERK 0.0
#endif

#ifndef MOTION_JD_JERK
    #define MOTION_JD_JERK AXIS_X_JERK
#endif

#ifndef MOTION_JD_HANDLE_SMALL_SEGMENTS
    #define MOTION_JD_HANDLE_SMALL_SEGMENTS
#endif

#ifndef MOTION_JUNCTION_DEVIATION
    #define MOTION_JUNCTION_DEVIATION ( 0.4 * MOTION_JD_JERK * MOTION_JD_JERK / MOTION_DEFAULT_ACCELERATION )
#endif

#ifndef MOTION_S_CURVE_ACCELERATION
    #define MOTION_S_CURVE_ACCELERATION false
#endif

#ifndef MOTION_DISABLE_BEFORE_HOMING
    #define MOTION_DISABLE_BEFORE_HOMING false
#endif

#ifndef MOTION_SOFTWARE_ENDSTOPS_MIN
    #define MOTION_SOFTWARE_ENDSTOPS_MIN true
#endif

#ifndef MOTION_SOFTWARE_ENDSTOPS_MAX
    #define MOTION_SOFTWARE_ENDSTOPS_MAX true
#endif

#ifndef MOTION_SOFTWARE_ENDSTOPS_MENU_ITEM
    #define MOTION_SOFTWARE_ENDSTOPS_MENU_ITEM false
#endif

#ifndef MOTION_HOMING_FEEDRATE_XY
    #define MOTION_HOMING_FEEDRATE_XY (50*60)
#endif

#ifndef MOTION_HOMING_FEEDRATE_Z
    #define MOTION_HOMING_FEEDRATE_Z (4*60)
#endif

#ifndef MOTION_VALIDATE_HOMING_ENDSTOPS
    #define MOTION_VALIDATE_HOMING_ENDSTOPS true
#endif