/*
     _______.____    __    ____  ______   .______       _______  
    /       |\   \  /  \  /   / /  __  \  |   _  \     |       \ 
   |   (----` \   \/    \/   / |  |  |  | |  |_)  |    |  .--.  |
    \   \      \            /  |  |  |  | |      /     |  |  |  |
.----)   |      \    /\    /   |  `--'  | |  |\  \----.|  '--'  |
|_______/        \__/  \__/     \______/  | _| `._____||_______/ 
               _______  __       _______. __    __              
              |   ____||  |     /       ||  |  |  |
              |  |__   |  |    |   (----`|  |__|  | 
              |   __|  |  |     \   \    |   __   | 
              |  |     |  | .----)   |   |  |  |  | 
              |__|     |__| |_______/    |__|  |__| 
              F    I    R    M    W    A    R    E
*/
/***********************************************************************/
#pragma once
#include "Printer.h"
/***********************************************************************/
#define CONFIGURATION_H_VERSION 020007
/***********************************************************************/
// ┌───────────────┐
// │ @section info │
// ├───────────────┤
// │               │
// └───────────────┘

#define STRING_CONFIG_H_AUTOR   "SWORDFISH"
#define CUSTOM_VERSION_FILE     Version.h
#define SHOW_BOOTSCREEN

#if ENABLED(PRINTER_CUSTOM_BOOTSCREEN)
    #define SHOW_CUSTOM_BOOTSCREEN
#endif

#if ENABLED(PRINTER_CUSTOM_STATUS_SCREEN)
    #define CUSTOM_STATUS_SCREEN_IMAGE
#endif

/***********************************************************************/
// ┌──────────────────┐
// │ @section machine │
// ├──────────────────┤
// │                  │
// └──────────────────┘

#if ENABLED(PRINTER_SERIAL_PORT_ENABLE)
    #define SERIAL_PORT PRINTER_SERIAL_PORT_ID
#endif

#if ENABLED(PRINTER_SERIAL_PORT_2_ENABLE)
    #define SERIAL_PORT_2 PRINTER_SERIAL_PORT_2_ID
#endif

#define BAUDRATE PRINTER_BAUDRATE

#ifdef PRINTER_MOTHERBOARD
    #define MOTHERBOARD PRINTER_MOTHERBOARD
#endif

#ifdef PRINTER_NAME
    #define CUSTOM_MACHINE_NAME PRINTER_NAME
#endif

#ifdef PRINTER_MACHINE_UUID
    #define MACHINE_UUID PRINTER_MACHINE_UUID
#endif

#if ENABLED(PSU_CONTROL)
    #if ENABLED(PSU_AUTO_POWER_CONTROL)
        #define AUTO_POWER_CONTROL
        #if ENABLED(PSU_AUTO_POWER_FANS)
            #define AUTO_POWER_FANS 
        #endif 
        #if ENABLED(PSU_AUTO_POWER_E_FANS)
            #define AUTO_POWER_E_FANS
        #endif
        #if ENABLED(PSU_AUTO_POWER_CONTROLLERFAN)
            #define AUTO_POWER_CONTROLLERFAN
        #endif
        #if ENABLED(PSU_AUTO_POWER_CHAMBER_FAN)
            #define AUTO_POWER_CHAMBER_FAN
        #endif
        #define AUTO_POWER_E_TEMP  PSU_AUTO_POWER_E_TEMP
        #define AUTO_POWER_CHAMBER_TEMP PSU_AUTO_POWER_CHAMBER_TEMP
        #define POWER_TIMEOUT PSU_POWER_TIMEOUT
    #endif
#endif

#if IS_PRINTER_MOTION(corexy)
    #define COREXY
#endif
#if IS_PRINTER_MOTION(corexz)
    #define COREXZ
#endif
#if IS_PRINTER_MOTION(coreyz)
    #define COREYZ
#endif
#if IS_PRINTER_MOTION(coreyx)
    #define COREYX
#endif
#if IS_PRINTER_MOTION(corezx)
    #define COREZX
#endif
#if IS_PRINTER_MOTION(corezy)
    #define COREZY
#endif
#if IS_PRINTER_MOTION(markforged_xy)
    #define MARKFORGED_XY
#endif

/***********************************************************************/
// ┌───────────────────┐
// │ @section extruder │
// ├───────────────────┤
// │                   │
// └───────────────────┘

#define EXTRUDERS EXTRUDER_NUMBERS

#define DEFAULT_NOMINAL_FILAMENT_DIA EXTRUDER_FILAMENT_DIAMETER

#if ENABLED(EXTRUDER_SINGLENOZZLE)
    #define SINGLENOZZLE
    #if ENABLED(EXTRUDER_SINGLENOZZLE_STANDBY_TEMP)
        #define SINGLENOZZLE_STANDBY_TEMP
    #endif
    #if ENABLED(EXTRUDER_SINGLENOZZLE_STANDBY_FAN)
        #define SINGLENOZZLE_STANDBY_FAN
    #endif
#endif

#if ENABLED(EXTRUDER_SWITCHING)
    #define SWITCHING_EXTRUDER
    #define SWITCHING_EXTRUDER_SERVO_NR EXTRUDER_SWITCHING_SERVO_NR
    #define SWITCHING_EXTRUDER_SERVO_ANGLES EXTRUDER_SWITCHING_SERVO_ANGLES
    #if EXTRUDERS > 3
        #define SWITCHING_EXTRUDER_E23_SERVO_NR EXTRUDER_SWITCHING_E23_SERVO_NR
    #endif
#endif

#if ENABLED(EXTRUDER_SWITCHING_NOZZLE)
    #define SWITCHING_NOZZLE
    #define SWITCHING_NOZZLE_SERVO_NR EXTRUDER_SWITCHING_NOZZLE_SERVO_NR
    #ifdef EXTRUDER_SWITCHING_NOZZLE_E1_SERVO_NR
        #define SWITCHING_NOZZLE_E1_SERVO_NR EXTRUDER_SWITCHING_NOZZLE_E1_SERVO_NR
    #endif
#endif

#if ENABLED(EXTRUDER_PARKING)
    #define PARKING_EXTRUDER
    #if ENABLED(EXTRUDER_PARKING_SOLENOIDS_INVERT)
        #define PARKING_EXTRUDER_SOLENOIDS_INVERT
    #endif
    #define PARKING_EXTRUDER_SOLENOIDS_PINS_ACTIVE EXTRUDER_PARKING_SOLENOIDS_PINS_ACTIVE
    #define PARKING_EXTRUDER_SOLENOIDS_DELAY EXTRUDER_PARKING_SOLENOIDS_DELAY
#endif

#if ENABLED(EXTRUDER_PARKING_MAGNETIC)
    #define MAGNETIC_PARKING_EXTRUDER
    #define MPE_FAST_SPEED EXTRUDER_PARKING_MAGNETIC_FAST_SPEED
    #define MPE_SLOW_SPEED EXTRUDER_PARKING_MAGNETIC_SLOW_SPEED
    #define MPE_TRAVEL_DISTANCE EXTRUDER_PARKING_MAGNETIC_TRAVEL_DISTANCE
    #define MPE_COMPENSATION EXTRUDER_PARKING_MAGNETIC_COMPENSATION
#endif

#if EITHER(PARKING_EXTRUDER,MAGNETIC_PARKING_EXTRUDER)
    #define PARKING_EXTRUDER_PARKING_X EXTRUDER_PARKING_X
    #define PARKING_EXTRUDER_GRAB_POSITION EXTRUDER_PARKING_GRAB_POSITION
    #if ENABLED(EXTRUDER_PARKING_MANUAL_SOLENOID_CONTROL)
        #define MANUAL_SOLENOID_CONTROL
    #endif
#endif

#if ENABLED(EXTRUDER_SWITCHING_TOOLHEAD)
    #define SWITCHING_TOOLHEAD
    #define SWITCHING_NOZZLE_SERVO_NR EXTRUDER_SWITCHING_TOOLHEAD_SERVO_NR
    #define SWITCHING_TOOLHEAD_SERVO_ANGLES EXTRUDER_SWITCHING_TOOLHEAD_SERVO_ANGLES
#endif

#if ENABLED(EXTRUDER_SWITCHING_TOOLHEAD_MAGNETIC)
    #define MAGNETIC_SWITCHING_TOOLHEAD
    #define SWITCHING_TOOLHEAD_Y_RELEASE EXTRUDER_SWITCHING_TOOLHEAD_Y_RELEASE
    #define SWITCHING_TOOLHEAD_X_SECURITY EXTRUDER_SWITCHING_TOOLHEAD_X_SECURITY
    #if ENABLED(EXTRUDER_SWITCHING_TOOLHEAD_PRIME_BEFORE_REMOVE)
        #define PRIME_BEFORE_REMOVE
        #define SWITCHING_TOOLHEAD_PRIME_MM EXTRUDER_SWITCHING_TOOLHEAD_PRIME_MM
        #define SWITCHING_TOOLHEAD_RETRACT_MM EXTRUDER_SWITCHING_TOOLHEAD_RETRACT_MM
        #define SWITCHING_TOOLHEAD_PRIME_FEEDRATE EXTRUDER_SWITCHING_TOOLHEAD_PRIME_FEEDRATE
        #define SWITCHING_TOOLHEAD_RETRACT_FEEDRATE EXTRUDER_SWITCHING_TOOLHEAD_RETRACT_FEEDRATE
    #endif
#endif

#if ENABLED(EXTRUDER_SWITCHING_TOOLHEAD_ELECTROMAGNETIC)
    #define ELECTROMAGNETIC_SWITCHING_TOOLHEAD
    #define SWITCHING_TOOLHEAD_Z_HOP EXTRUDER_SWITCHING_TOOLHEAD_Z_HOP
#endif

#if ANY(SWITCHING_TOOLHEAD,MAGNETIC_SWITCHING_TOOLHEAD,ELECTROMAGNETIC_SWITCHING_TOOLHEAD)
    #define SWITCHING_TOOLHEAD_Y_POS EXTRUDER_SWITCHING_TOOLHEAD_Y_POS
    #define SWITCHING_TOOLHEAD_Y_SECURITY EXTRUDER_SWITCHING_TOOLHEAD_Y_SECURITY
    #define SWITCHING_TOOLHEAD_Y_CLEAR EXTRUDER_SWITCHING_TOOLHEAD_Y_CLEAR
    #define SWITCHING_TOOLHEAD_X_POS EXTRUDER_SWITCHING_TOOLHEAD_X_POS
#endif

#if ENABLED(EXTRUDER_MIXING)
    #define MIXING_EXTRUDER
    #define MIXING_STEPPERS EXTRUDER_MIXING_STEPPERS
    #define MIXING_VIRTUAL_TOOLS EXTRUDER_MIXING_VIRTUAL_TOOLS
    #if ENABLED(EXTRUDER_MIXING_DIRECT_IN_G1)
        #define DIRECT_MIXING_IN_G1
    #endif
    #if ENABLED(EXTRUDER_MIXING_GRADIENT)
        #define GRADIENT_MIX
        #if ENABLED(EXTRUDER_MIXING_GRADIENT_VTOOL)
            #define GRADIENT_VTOOL
        #endif
    #endif
#endif

#ifdef EXTRUDER_HOTEND_OFFSET_X
    #define HOTEND_OFFSET_X EXTRUDER_HOTEND_OFFSET_X
#endif

#ifdef EXTRUDER_HOTEND_OFFSET_Y
    #define HOTEND_OFFSET_Y EXTRUDER_HOTEND_OFFSET_Y
#endif

#ifdef EXTRUDER_HOTEND_OFFSET_Z
    #define HOTEND_OFFSET_Z EXTRUDER_HOTEND_OFFSET_Z
#endif

#if ENABLED(EXTRUDER_PREVENT_COLD_EXTRUSION)
    #define PREVENT_COLD_EXTRUSION
#endif
#define EXTRUDE_MINTEMP EXTRUDER_MINTEMP

#if ENABLED(EXTRUDER_PREVENT_LENGTHY_EXTRUDE)
    #define PREVENT_LENGTHY_EXTRUDE
#endif
#define EXTRUDE_MAXLENGTH EXTRUDER_MAXLENGTH

#if ENABLED(HOTEND_THERMAL_RUNAWAY)
    #define THERMAL_PROTECTION_HOTENDS
#endif

#if ENABLED(BED_THERMAL_RUNAWAY)
    #define THERMAL_PROTECTION_BED
#endif

#if ENABLED(CHAMBER_THERMAL_RUNAWAY)
    #define THERMAL_PROTECTION_CHAMBER
#endif

/***********************************************************************/
// ┌──────────────────────┐
// │ @section temperature │
// ├──────────────────────┤
// │                      │
// └──────────────────────┘

#define TEMP_SENSOR_0 HOTEND_SENSOR_0 
#define TEMP_SENSOR_1 HOTEND_SENSOR_1
#define TEMP_SENSOR_2 HOTEND_SENSOR_2
#define TEMP_SENSOR_3 HOTEND_SENSOR_3
#define TEMP_SENSOR_4 HOTEND_SENSOR_4
#define TEMP_SENSOR_5 HOTEND_SENSOR_5
#define TEMP_SENSOR_6 HOTEND_SENSOR_6
#define TEMP_SENSOR_7 HOTEND_SENSOR_7
#define TEMP_SENSOR_BED BED_SENSOR
#define TEMP_SENSOR_PROBE HOTEND_SENSOR_PROBE
#define TEMP_SENSOR_CHAMBER CHAMBER_SENSOR

#if (HOTEND_SENSOR_0 == -5 || HOTEND_SENSOR_1 == -5)
    #define MAX31865_SENSOR_OHMS HOTEND_MAX31865_SENSOR_OHMS
    #define MAX31865_CALIBRATION_OHMS HOTEND_MAX31865_CALIBRATION_OHMS
#endif

#if ENABLED(HOTEND_SENSOR_1_AS_REDUNDANT)
    #define TEMP_SENSOR_1_AS_REDUNDANT
#endif
#define MAX_REDUNDANT_TEMP_SENSOR_DIFF HOTEND_MAX_REDUNDANT_DIFF

#define TEMP_RESIDENCY_TIME HOTEND_TEMP_RESIDENCY_TIME
#define TEMP_WINDOW HOTEND_TEMP_WINDOW

#define TEMP_HYSTERESIS HOTEND_TEMP_HYSTERESIS

#define TEMP_BED_RESIDENCY_TIME BED_TEMP_RESIDENCY_TIME
#define TEMP_BED_WINDOW BED_TEMP_WINDOW

#define TEMP_BED_HYSTERESIS BED_TEMP_HYSTERESIS

#define HEATER_0_MINTEMP HOTEND_SENSOR_0_MINTEMP
#define HEATER_1_MINTEMP HOTEND_SENSOR_1_MINTEMP
#define HEATER_2_MINTEMP HOTEND_SENSOR_2_MINTEMP
#define HEATER_3_MINTEMP HOTEND_SENSOR_3_MINTEMP
#define HEATER_4_MINTEMP HOTEND_SENSOR_4_MINTEMP
#define HEATER_5_MINTEMP HOTEND_SENSOR_5_MINTEMP
#define HEATER_6_MINTEMP HOTEND_SENSOR_6_MINTEMP
#define HEATER_7_MINTEMP HOTEND_SENSOR_7_MINTEMP
#define BED_MINTEMP BED_SENSOR_MINTEMP

#define HEATER_0_MAXTEMP HOTEND_SENSOR_0_MAXTEMP
#define HEATER_1_MAXTEMP HOTEND_SENSOR_1_MAXTEMP
#define HEATER_2_MAXTEMP HOTEND_SENSOR_2_MAXTEMP
#define HEATER_3_MAXTEMP HOTEND_SENSOR_3_MAXTEMP
#define HEATER_4_MAXTEMP HOTEND_SENSOR_4_MAXTEMP
#define HEATER_5_MAXTEMP HOTEND_SENSOR_5_MAXTEMP
#define HEATER_6_MAXTEMP HOTEND_SENSOR_6_MAXTEMP
#define HEATER_7_MAXTEMP HOTEND_SENSOR_7_MAXTEMP
#define BED_MAXTEMP BED_SENSOR_MAXTEMP

#if ENABLED(HOTEND_PID)
    #define PIDTEMP
    #define PID_MAX HOTEND_PID_MAX
    #define PID_K1 HOTEND_PID_K1
    #if ENABLED(HOTEND_PID_EDIT_MENU)
        #define PID_EDIT_MENU
    #endif
    #if ENABLED(HOTEND_PID_AUTOTUNE_MENU)
        #define PID_AUTOTUNE_MENU
    #endif
    #if ENABLED(HOTEND_PID_PARAMS_PER_HOTEND)
        #define PID_PARAMS_PER_HOTEND
        #define DEFAULT_Kp_LIST HOTEND_PID_KP_LIST
        #define DEFAULT_Ki_LIST HOTEND_PID_KI_LIST
        #define DEFAULT_Kd_LIST HOTEND_PID_KD_LIST
    #else
        #define DEFAULT_Kp HOTEND_PID_KP
        #define DEFAULT_Ki HOTEND_PID_KI
        #define DEFAULT_Kd HOTEND_PID_KD
    #endif
#endif
#define BANG_MAX HOTEND_BANG_MAX

#if ENABLED(BED_PID)
    #define PIDBEDTEMP
    #if ENABLED(BED_PID_DEBUG)
        #define PID_BED_DEBUG
    #endif
    #define DEFAULT_bedKp BED_PID_KP
    #define DEFAULT_bedKi BED_PID_KI
    #define DEFAULT_bedKd BED_PID_KD
#endif

#define MAX_BED_POWER BED_MAX_POWER
#define MIN_BED_POWER BED_MIN_POWER

#if EITHER(HOTEND_PID, BED_PID)
    #if ENABLED(PRINTER_PID_DEBUG)
        #define PID_DEBUG
    #endif
    #if ENABLED(PRINTER_PID_OPENLOOP)
        #define PID_OPENLOOP
    #endif
    #if ENABLED(PRINTER_SLOW_PWM_HEATERS)
        #define SLOW_PWM_HEATERS
    #endif
    #define PID_FUNCTIONAL_RANGE PRINTER_PID_FUNCTIONAL_RANGE
#endif

/***********************************************************************/
// ┌─────────────────┐
// │ @section homing │
// ├─────────────────┤
// │                 │
// └─────────────────┘

#if ENABLED(AXIS_X_ENDSTOP_MIN)
    #define USE_XMIN_PLUG
#endif

#if ENABLED(AXIS_X_ENDSTOP_MAX)
    #define USE_XMAX_PLUG
#endif

#if ENABLED(AXIS_Y_ENDSTOP_MIN)
    #define USE_YMIN_PLUG
#endif

#if ENABLED(AXIS_Y_ENDSTOP_MAX)
    #define USE_YMAX_PLUG
#endif

#if ENABLED(AXIS_Z_ENDSTOP_MIN)
    #define USE_ZMIN_PLUG
#endif

#if ENABLED(AXIS_Z_ENDSTOP_MAX)
    #define USE_ZMAX_PLUG
#endif

#if ENABLED(PRINTER_ENDSTOP_PULLUP)
    #define ENDSTOPPULLUPS
#endif

#if DISABLED(PRINTER_ENDSTOP_PULLUP)
    #if ENABLED(AXIS_X_ENDSTOP_MAX_PULLUP)
        #define ENDSTOPPULLUPS_XMAX
    #endif
    #if ENABLED(AXIS_Y_ENDSTOP_MAX_PULLUP)
        #define ENDSTOPPULLUPS_YMAX
    #endif
    #if ENABLED(AXIS_Z_ENDSTOP_MAX_PULLUP)
        #define ENDSTOPPULLUPS_ZMAX
    #endif
    #if ENABLED(AXIS_X_ENDSTOP_MIN_PULLUP)
        #define ENDSTOPPULLUPS_XMIN
    #endif
    #if ENABLED(AXIS_Y_ENDSTOP_MIN_PULLUP)
        #define ENDSTOPPULLUPS_YMIN
    #endif
    #if ENABLED(AXIS_Z_ENDSTOP_MIN_PULLUP)
        #define ENDSTOPPULLUPS_ZMIN
    #endif
    #if ENABLED(AXIS_Z_ENDSTOP_MIN_PROBE_PULLUP)
        #define ENDSTOPPULLUPS_ZMIN_PROBE
    #endif
#endif

#if ENABLED(PRINTER_ENDSTOP_PULLDOWN)
    #define ENDSTOPPULLDOWNS
#endif

#if DISABLED(PRINTER_ENDSTOP_PULLDOWN)
    #if ENABLED(AXIS_X_ENDSTOP_MAX_PULLDOWN)
        #define ENDSTOPPULLDOWN_XMAX
    #endif
    #if ENABLED(AXIS_Y_ENDSTOP_MAX_PULLDOWN)
        #define ENDSTOPPULLDOWN_YMAX
    #endif
    #if ENABLED(AXIS_Z_ENDSTOP_MAX_PULLDOWN)
        #define ENDSTOPPULLDOWN_ZMAX
    #endif
    #if ENABLED(AXIS_X_ENDSTOP_MIN_PULLDOWN)
        #define ENDSTOPPULLDOWN_XMIN
    #endif
    #if ENABLED(AXIS_Y_ENDSTOP_MIN_PULLDOWN)
        #define ENDSTOPPULLDOWN_YMIN
    #endif
    #if ENABLED(AXIS_Z_ENDSTOP_MIN_PULLDOWN)
        #define ENDSTOPPULLDOWN_ZMIN
    #endif
    #if ENABLED(AXIS_Z_ENDSTOP_MIN_PROBE_PULLDOWN)
        #define ENDSTOPPULLDOWN_ZMIN_PROBE
    #endif
#endif

#define X_MIN_ENDSTOP_INVERTING AXIS_X_ENDSTOP_MIN_INVERTING
#define Y_MIN_ENDSTOP_INVERTING AXIS_Y_ENDSTOP_MIN_INVERTING
#define Z_MIN_ENDSTOP_INVERTING AXIS_Z_ENDSTOP_MIN_INVERTING
#define X_MAX_ENDSTOP_INVERTING AXIS_X_ENDSTOP_MAX_INVERTING
#define Y_MAX_ENDSTOP_INVERTING AXIS_Y_ENDSTOP_MAX_INVERTING
#define Z_MAX_ENDSTOP_INVERTING AXIS_Z_ENDSTOP_MAX_INVERTING
#define Z_MIN_PROBE_ENDSTOP_INVERTING AXIS_Z_ENDSTOP_MIN_PROBE_INVERTING

#define X_DRIVER_TYPE  AXIS_X_DRIVER
#define Y_DRIVER_TYPE  AXIS_Y_DRIVER
#define Z_DRIVER_TYPE  AXIS_Z_DRIVER
#define X2_DRIVER_TYPE AXIS_X2_DRIVER
#define Y2_DRIVER_TYPE AXIS_X2_DRIVER
#define Z2_DRIVER_TYPE AXIS_Z2_DRIVER
#define Z3_DRIVER_TYPE AXIS_Z3_DRIVER
#define Z4_DRIVER_TYPE AXIS_Z4_DRIVER
#define E0_DRIVER_TYPE AXIS_E0_DRIVER
#define E1_DRIVER_TYPE AXIS_E1_DRIVER
#define E2_DRIVER_TYPE AXIS_E2_DRIVER
#define E3_DRIVER_TYPE AXIS_E3_DRIVER
#define E4_DRIVER_TYPE AXIS_E4_DRIVER
#define E5_DRIVER_TYPE AXIS_E5_DRIVER
#define E6_DRIVER_TYPE AXIS_E6_DRIVER
#define E7_DRIVER_TYPE AXIS_E7_DRIVER

#if ENABLED(PRINTER_ENDSTOP_INTERRUPTS_FEATURE)
    #define ENDSTOP_INTERRUPTS_FEATURE
#endif

#if PRINTER_ENDSTOP_NOISE_THRESOLD > 0
    #define ENDSTOP_NOISE_THRESOLD PRINTER_ENDSTOP_NOISE_THRESOLD
#endif

#if ENABLED(PRINTER_DETECT_BROKEN_ENDSTOP)
    #define DETECT_BROKEN_ENDSTOP
#endif

/***********************************************************************/
// ┌─────────────────┐
// │ @section motion │
// ├─────────────────┤
// │                 │
// └─────────────────┘

#if ENABLED(MOTION_DISTINCT_E_FACTORS)
    #define DISTINCT_E_FACTORS
    #define ALL_E_STEPS_MM AXIS_VALUE_LIST(EXTRUDER_NUMBERS,E,STEPS_MM)
    #define ALL_E_MAX_FEEDRATE AXIS_VALUE_LIST(EXTRUDER_NUMBERS,E,MAX_FEEDRATE)
    #define ALL_E_MAX_ACCELERATION AXIS_VALUE_LIST(EXTRUDER_NUMBERS,E,MAX_ACCELERATION)
#else
    #define ALL_E_STEPS_MM AXIS_E0_STEPS_MM
    #define ALL_E_MAX_FEEDRATE AXIS_E0_MAX_FEEDRATE
    #define ALL_E_MAX_ACCELERATION AXIS_E0_MAX_ACCELERATION
#endif

#define DEFAULT_AXIS_STEPS_PER_UNIT { AXIS_X_STEPS_MM, AXIS_Y_STEPS_MM, AXIS_Z_STEPS_MM, ALL_E_STEPS_MM }

#define DEFAULT_MAX_FEEDRATE { AXIS_X_MAX_FEEDRATE, AXIS_Y_MAX_FEEDRATE, AXIS_Z_MAX_FEEDRATE, ALL_E_MAX_FEEDRATE }

#if ENABLED(MOTION_LIMITED_MAX_FEEDRATE_EDITING)
    #define LIMITED_MAX_FR_EDITING
    #define MAX_FEEDRATE_EDIT_VALUES { AXIS_X_MAX_FEEDRATE_EDIT_VALUE, AXIS_Y_MAX_FEEDRATE_EDIT_VALUE, AXIS_Z_MAX_FEEDRATE_EDIT_VALUE, AXIS_E0_MAX_FEEDRATE_EDIT_VALUE }
#endif

#define DEFAULT_MAX_ACCELERATION { AXIS_X_MAX_ACCELERATION, AXIS_Y_MAX_ACCELERATION, AXIS_Z_MAX_ACCELERATION, ALL_E_MAX_ACCELERATION }

#if ENABLED(MOTION_LIMITED_MAX_ACCELERATION_EDITING)
    #define LIMITED_MAX_ACCEL_EDITING
    #define MAX_ACCEL_EDIT_VALUES { AXIS_X_MAX_ACCELERATION_EDIT_VALUE, AXIS_Y_MAX_FEEDRATE_EDIT_VALUE, AXIS_Z_MAX_ACCELERATION_EDIT_VALUE, AXIS_E0_MAX_ACCELERATION_EDIT_VALUE }
#endif

#define DEFAULT_ACCELERATION MOTION_DEFAULT_ACCELERATION
#define DEFAULT_RETRACT_ACCELERATION MOTION_DEFAULT_RETRACT_ACCELERATION
#define DEFAULT_TRAVEL_ACCELERATION MOTION_DEFAULT_TRAVEL_ACCELERATION







