/*
     _______.____    __    ____  ______   .______       _______  
    /       |\   \  /  \  /   / /  __  \  |   _  \     |       \ 
   |   (----` \   \/    \/   / |  |  |  | |  |_)  |    |  .--.  |
    \   \      \            /  |  |  |  | |      /     |  |  |  |
.----)   |      \    /\    /   |  `--'  | |  |\  \----.|  '--'  |
|_______/        \__/  \__/     \______/  | _| `._____||_______/ 
               _______  __       _______. __    __              
              |   ____||  |     /       ||  |  |  |
              |  |__   |  |    |   (----`|  |__|  | 
              |   __|  |  |     \   \    |   __   | 
              |  |     |  | .----)   |   |  |  |  | 
              |__|     |__| |_______/    |__|  |__| 
              F    I    R    M    W    A    R    E
*/
/* ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
 *                          ┌───────────┐
 *                          │ ATTENTION │
 *                          └───────────┘
 *        TO CONFIGURE THE PRINTER, USE THE PRINTER.H FILE
 *         IT IS NOT NECESSARY TO EDIT THIS FILE DIRECTLY
 * ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
********************************************************************** */

/* **********************************************************************
   `.---------------------------------------------------------------------             
  -syso+ooooooooooooooooooooooooooooooooooooooooooooooooooo++osmNNNNNNNNNNN`            
 /d/`                                                          -yNMMMMMMMMM`            
 m+     .:+++:` .:++/:`                          ydd`  /+.       -yNMMMMMMM`            
`N:   .yNMmmNNdyNNmmNMm+                         dMM` .mms         :hNMMMMM`            
`N:   hMN/.`.sMMN:.`.yMM/  `:+oo/-`     `:+oo/-  dMM` `oo/    -/oo+:.:hMMMM`            
`N:   NMd    .MMh    -MMs`+mMNmmNNd:   /mMNmmMNy`dMM` .MMh  .hNMmmNMd:`:hMM`            
`N:   NMd    .MMh    -MMs+MMy.``-dMN- .NMd.`.oMM+dMM` .MMh  yMM/``-NMm  `+M`            
`N:   NMd    .MMh    -MMshMM-    /MMo -MMs   `--.dMM` .MMh  dMM`   dMM`  :M`            
`N:   NMd    .MMh    -MMs/NMd/--./MMs-+MMs       sMM+-.MMh.-dMM`   dMM`  :M`            
 N/   NNd    `NNh    -NNs :ymNNNo:NNNNNNNs       `ymNN:NNNNNNNN`   hNN`  :N`            
 od-  ---     --.    `--.   `---.`-------.         .--`--------    ---  .ds             
  /ys+////////////////////////////////////////////////////////////////+sh/              
    .:////////////////////////////////////////////////////////////////:.   

        THIS VERSION OF SWORDFISH IS POWERD BY MARLIN FIRMWARE
 ********************************************************************* */
#pragma once
#include "Printer.h"
/***********************************************************************/
#define CONFIGURATION_H_VERSION 020007
/***********************************************************************/
// ┌───────────────┐
// │ @section info │
// ├───────────────┤
// │               │
// └───────────────┘

#define STRING_CONFIG_H_AUTOR   "SWORDFISH"
#define CUSTOM_VERSION_FILE     Version.h
#define SHOW_BOOTSCREEN

#if ENABLED(PRINTER_CUSTOM_BOOTSCREEN)
    #define SHOW_CUSTOM_BOOTSCREEN
#endif

#if ENABLED(PRINTER_CUSTOM_STATUS_SCREEN)
    #define CUSTOM_STATUS_SCREEN_IMAGE
#endif

/***********************************************************************/
// ┌──────────────────┐
// │ @section machine │
// ├──────────────────┤
// │                  │
// └──────────────────┘

#if ENABLED(PRINTER_SERIAL_PORT_ENABLE)
    #define SERIAL_PORT PRINTER_SERIAL_PORT_ID
#endif

#if ENABLED(PRINTER_SERIAL_PORT_2_ENABLE)
    #define SERIAL_PORT_2 PRINTER_SERIAL_PORT_2_ID
#endif

#define BAUDRATE PRINTER_BAUDRATE

#ifdef PRINTER_MOTHERBOARD
    #define MOTHERBOARD PRINTER_MOTHERBOARD
#endif

#ifdef PRINTER_NAME
    #define CUSTOM_MACHINE_NAME PRINTER_NAME
#endif

#ifdef PRINTER_MACHINE_UUID
    #define MACHINE_UUID PRINTER_MACHINE_UUID
#endif

#if ENABLED(PSU_CONTROL)
    #if ENABLED(PSU_AUTO_POWER_CONTROL)
        #define AUTO_POWER_CONTROL
        #if ENABLED(PSU_AUTO_POWER_FANS)
            #define AUTO_POWER_FANS 
        #endif 
        #if ENABLED(PSU_AUTO_POWER_E_FANS)
            #define AUTO_POWER_E_FANS
        #endif
        #if ENABLED(PSU_AUTO_POWER_CONTROLLERFAN)
            #define AUTO_POWER_CONTROLLERFAN
        #endif
        #if ENABLED(PSU_AUTO_POWER_CHAMBER_FAN)
            #define AUTO_POWER_CHAMBER_FAN
        #endif
        #define AUTO_POWER_E_TEMP  PSU_AUTO_POWER_E_TEMP
        #define AUTO_POWER_CHAMBER_TEMP PSU_AUTO_POWER_CHAMBER_TEMP
        #define POWER_TIMEOUT PSU_POWER_TIMEOUT
    #endif
#endif

#if PRINTER_HAS(MOTION,corexy)
    #define COREXY
#endif
#if PRINTER_HAS(MOTION,corexz)
    #define COREXZ
#endif
#if PRINTER_HAS(MOTION,coreyz)
    #define COREYZ
#endif
#if PRINTER_HAS(MOTION,coreyx)
    #define COREYX
#endif
#if PRINTER_HAS(MOTION,corezx)
    #define COREZX
#endif
#if PRINTER_HAS(MOTION,corezy)
    #define COREZY
#endif
#if PRINTER_HAS(MOTION,markforged_xy)
    #define MARKFORGED_XY
#endif

#define INVERT_X_DIR AXIS_X_INVERT_DIR
#define INVERT_Y_DIR AXIS_Y_INVERT_DIR
#define INVERT_Z_DIR AXIS_Z_INVERT_DIR

#define X_BED_SIZE BED_X_SIZE
#define Y_BED_SIZE BED_Y_SIZE

#define X_MIN_POS AXIS_X_MIN_POS
#define Y_MIN_POS AXIS_Y_MIN_POS
#define Z_MIN_POS AXIS_Z_MIN_POS
#define X_MAX_POS AXIS_X_MAX_POS
#define Y_MAX_POS AXIS_Y_MAX_POS
#define Z_MAX_POS AXIS_Z_MAX_POS

#if ENABLED(MOTION_SOFTWARE_ENDSTOPS_MIN)
    #define MIN_SOFTWARE_ENDSTOPS
    #if ENABLED(AXIS_X_SOFTWARE_ENDSTOP_MIN)
        #define MIN_SOFTWARE_ENDSTOP_X
    #endif
    #if ENABLED(AXIS_Y_SOFTWARE_ENDSTOP_MIN)
        #define MIN_SOFTWARE_ENDSTOP_Y
    #endif
    #if ENABLED(AXIS_Z_SOFTWARE_ENDSTOP_MIN)
        #define MIN_SOFTWARE_ENDSTOP_Z
    #endif
#endif

#if ENABLED(MOTION_SOFTWARE_ENDSTOPS_MAX)
    #define MAX_SOFTWARE_ENDSTOPS
    #if ENABLED(AXIS_X_SOFTWARE_ENDSTOP_MAX)
        #define MAX_SOFTWARE_ENDSTOP_X
    #endif
    #if ENABLED(AXIS_Y_SOFTWARE_ENDSTOP_MAX)
        #define MAX_SOFTWARE_ENDSTOP_Y
    #endif
    #if ENABLED(AXIS_Z_SOFTWARE_ENDSTOP_MAX)
        #define MAX_SOFTWARE_ENDSTOP_Z
    #endif
#endif

#if EITHER(MOTION_SOFTWARE_ENDSTOPS_MIN, MOTION_SOFTWARE_ENDSTOPS_MAX)
    #if ENABLED(MOTION_SOFTWARE_ENDSTOPS_MENU_ITEM)
        #define SOFT_ENDSTOPS_MENU_ITEM
    #endif
#endif


#if ENABLED(PRINTER_FILAMENT_RUNOUT)
    #define FILAMENT_RUNOUT_SENSOR
    #define FIL_RUNOUT_ENABLED_DEFAULT PRINTER_FILAMENT_RUNOUT_ENABLED_DEFAULT
    #define NUM_RUNOUT_SENSORS PRINTER_FILAMENT_RUNOUT_NUMBERS
    #define FIL_RUNOUT_STATE PRINTER_FILAMENT_RUNOUT_STATE
    #if ENABLED(PRINTER_FILAMENT_RUNOUT_PULLUP)
        #define FIL_RUNOUT_PULLUP 
    #endif
    #if ENABLED(PRINTER_FILAMENT_RUNOUT_PULLDOWN)
        #define FIL_RUNOUT_PULLDOWN 
    #endif
    #define FILAMENT_RUNOUT_SCRIPT PRINTER_FILAMENT_RUNOUT_SCRIPT
    #if PRINTER_FILAMENT_RUNOUT_DISTANCE_MM > 0
        #define FILAMENT_RUNOUT_DISTANCE_MM PRINTER_FILAMENT_RUNOUT_DISTANCE_MM
        #if ENABLED(PRINTER_FILAMENT_RUNOUT_MOTION_SENSOR)
            #define FILAMENT_MOTION_SENSOR
        #endif
    #endif
#endif

/***********************************************************************/
// ┌───────────────────┐
// │ @section extruder │
// ├───────────────────┤
// │                   │
// └───────────────────┘

#define EXTRUDERS EXTRUDER_NUMBERS

#define DEFAULT_NOMINAL_FILAMENT_DIA EXTRUDER_FILAMENT_DIAMETER

#if ENABLED(EXTRUDER_SINGLENOZZLE)
    #define SINGLENOZZLE
    #if ENABLED(EXTRUDER_SINGLENOZZLE_STANDBY_TEMP)
        #define SINGLENOZZLE_STANDBY_TEMP
    #endif
    #if ENABLED(EXTRUDER_SINGLENOZZLE_STANDBY_FAN)
        #define SINGLENOZZLE_STANDBY_FAN
    #endif
#endif

#if ENABLED(EXTRUDER_SWITCHING)
    #define SWITCHING_EXTRUDER
    #define SWITCHING_EXTRUDER_SERVO_NR EXTRUDER_SWITCHING_SERVO_NR
    #define SWITCHING_EXTRUDER_SERVO_ANGLES EXTRUDER_SWITCHING_SERVO_ANGLES
    #if EXTRUDERS > 3
        #define SWITCHING_EXTRUDER_E23_SERVO_NR EXTRUDER_SWITCHING_E23_SERVO_NR
    #endif
#endif

#if ENABLED(EXTRUDER_SWITCHING_NOZZLE)
    #define SWITCHING_NOZZLE
    #define SWITCHING_NOZZLE_SERVO_NR EXTRUDER_SWITCHING_NOZZLE_SERVO_NR
    #ifdef EXTRUDER_SWITCHING_NOZZLE_E1_SERVO_NR
        #define SWITCHING_NOZZLE_E1_SERVO_NR EXTRUDER_SWITCHING_NOZZLE_E1_SERVO_NR
    #endif
#endif

#if ENABLED(EXTRUDER_PARKING)
    #define PARKING_EXTRUDER
    #if ENABLED(EXTRUDER_PARKING_SOLENOIDS_INVERT)
        #define PARKING_EXTRUDER_SOLENOIDS_INVERT
    #endif
    #define PARKING_EXTRUDER_SOLENOIDS_PINS_ACTIVE EXTRUDER_PARKING_SOLENOIDS_PINS_ACTIVE
    #define PARKING_EXTRUDER_SOLENOIDS_DELAY EXTRUDER_PARKING_SOLENOIDS_DELAY
#endif

#if ENABLED(EXTRUDER_PARKING_MAGNETIC)
    #define MAGNETIC_PARKING_EXTRUDER
    #define MPE_FAST_SPEED EXTRUDER_PARKING_MAGNETIC_FAST_SPEED
    #define MPE_SLOW_SPEED EXTRUDER_PARKING_MAGNETIC_SLOW_SPEED
    #define MPE_TRAVEL_DISTANCE EXTRUDER_PARKING_MAGNETIC_TRAVEL_DISTANCE
    #define MPE_COMPENSATION EXTRUDER_PARKING_MAGNETIC_COMPENSATION
#endif

#if EITHER(PARKING_EXTRUDER,MAGNETIC_PARKING_EXTRUDER)
    #define PARKING_EXTRUDER_PARKING_X EXTRUDER_PARKING_X
    #define PARKING_EXTRUDER_GRAB_POSITION EXTRUDER_PARKING_GRAB_POSITION
    #if ENABLED(EXTRUDER_PARKING_MANUAL_SOLENOID_CONTROL)
        #define MANUAL_SOLENOID_CONTROL
    #endif
#endif

#if ENABLED(EXTRUDER_SWITCHING_TOOLHEAD)
    #define SWITCHING_TOOLHEAD
    #define SWITCHING_NOZZLE_SERVO_NR EXTRUDER_SWITCHING_TOOLHEAD_SERVO_NR
    #define SWITCHING_TOOLHEAD_SERVO_ANGLES EXTRUDER_SWITCHING_TOOLHEAD_SERVO_ANGLES
#endif

#if ENABLED(EXTRUDER_SWITCHING_TOOLHEAD_MAGNETIC)
    #define MAGNETIC_SWITCHING_TOOLHEAD
    #define SWITCHING_TOOLHEAD_Y_RELEASE EXTRUDER_SWITCHING_TOOLHEAD_Y_RELEASE
    #define SWITCHING_TOOLHEAD_X_SECURITY EXTRUDER_SWITCHING_TOOLHEAD_X_SECURITY
    #if ENABLED(EXTRUDER_SWITCHING_TOOLHEAD_PRIME_BEFORE_REMOVE)
        #define PRIME_BEFORE_REMOVE
        #define SWITCHING_TOOLHEAD_PRIME_MM EXTRUDER_SWITCHING_TOOLHEAD_PRIME_MM
        #define SWITCHING_TOOLHEAD_RETRACT_MM EXTRUDER_SWITCHING_TOOLHEAD_RETRACT_MM
        #define SWITCHING_TOOLHEAD_PRIME_FEEDRATE EXTRUDER_SWITCHING_TOOLHEAD_PRIME_FEEDRATE
        #define SWITCHING_TOOLHEAD_RETRACT_FEEDRATE EXTRUDER_SWITCHING_TOOLHEAD_RETRACT_FEEDRATE
    #endif
#endif

#if ENABLED(EXTRUDER_SWITCHING_TOOLHEAD_ELECTROMAGNETIC)
    #define ELECTROMAGNETIC_SWITCHING_TOOLHEAD
    #define SWITCHING_TOOLHEAD_Z_HOP EXTRUDER_SWITCHING_TOOLHEAD_Z_HOP
#endif

#if ANY(SWITCHING_TOOLHEAD,MAGNETIC_SWITCHING_TOOLHEAD,ELECTROMAGNETIC_SWITCHING_TOOLHEAD)
    #define SWITCHING_TOOLHEAD_Y_POS EXTRUDER_SWITCHING_TOOLHEAD_Y_POS
    #define SWITCHING_TOOLHEAD_Y_SECURITY EXTRUDER_SWITCHING_TOOLHEAD_Y_SECURITY
    #define SWITCHING_TOOLHEAD_Y_CLEAR EXTRUDER_SWITCHING_TOOLHEAD_Y_CLEAR
    #define SWITCHING_TOOLHEAD_X_POS EXTRUDER_SWITCHING_TOOLHEAD_X_POS
#endif

#if ENABLED(EXTRUDER_MIXING)
    #define MIXING_EXTRUDER
    #define MIXING_STEPPERS EXTRUDER_MIXING_STEPPERS
    #define MIXING_VIRTUAL_TOOLS EXTRUDER_MIXING_VIRTUAL_TOOLS
    #if ENABLED(EXTRUDER_MIXING_DIRECT_IN_G1)
        #define DIRECT_MIXING_IN_G1
    #endif
    #if ENABLED(EXTRUDER_MIXING_GRADIENT)
        #define GRADIENT_MIX
        #if ENABLED(EXTRUDER_MIXING_GRADIENT_VTOOL)
            #define GRADIENT_VTOOL
        #endif
    #endif
#endif

#ifdef EXTRUDER_HOTEND_OFFSET_X
    #define HOTEND_OFFSET_X EXTRUDER_HOTEND_OFFSET_X
#endif

#ifdef EXTRUDER_HOTEND_OFFSET_Y
    #define HOTEND_OFFSET_Y EXTRUDER_HOTEND_OFFSET_Y
#endif

#ifdef EXTRUDER_HOTEND_OFFSET_Z
    #define HOTEND_OFFSET_Z EXTRUDER_HOTEND_OFFSET_Z
#endif

#if ENABLED(EXTRUDER_PREVENT_COLD_EXTRUSION)
    #define PREVENT_COLD_EXTRUSION
#endif
#define EXTRUDE_MINTEMP EXTRUDER_MINTEMP

#if ENABLED(EXTRUDER_PREVENT_LENGTHY_EXTRUDE)
    #define PREVENT_LENGTHY_EXTRUDE
#endif
#define EXTRUDE_MAXLENGTH EXTRUDER_MAXLENGTH

#if ENABLED(HOTEND_THERMAL_RUNAWAY)
    #define THERMAL_PROTECTION_HOTENDS
#endif

#if ENABLED(BED_THERMAL_RUNAWAY)
    #define THERMAL_PROTECTION_BED
#endif

#if ENABLED(CHAMBER_THERMAL_RUNAWAY)
    #define THERMAL_PROTECTION_CHAMBER
#endif

#define DISABLE_E AXIS_E0_DISABLE
#define DISABLE_INACTIVE_EXTRUDER EXTRUDER_DISABLE_INACTIVE

#define INVERT_E0_DIR AXIS_E0_INVERT_DIR
#define INVERT_E1_DIR AXIS_E1_INVERT_DIR
#define INVERT_E2_DIR AXIS_E2_INVERT_DIR
#define INVERT_E3_DIR AXIS_E3_INVERT_DIR
#define INVERT_E4_DIR AXIS_E4_INVERT_DIR
#define INVERT_E5_DIR AXIS_E5_INVERT_DIR
#define INVERT_E6_DIR AXIS_E6_INVERT_DIR
#define INVERT_E7_DIR AXIS_E7_INVERT_DIR
/***********************************************************************/
// ┌──────────────────────┐
// │ @section temperature │
// ├──────────────────────┤
// │                      │
// └──────────────────────┘

#define TEMP_SENSOR_0 HOTEND_SENSOR_0 
#define TEMP_SENSOR_1 HOTEND_SENSOR_1
#define TEMP_SENSOR_2 HOTEND_SENSOR_2
#define TEMP_SENSOR_3 HOTEND_SENSOR_3
#define TEMP_SENSOR_4 HOTEND_SENSOR_4
#define TEMP_SENSOR_5 HOTEND_SENSOR_5
#define TEMP_SENSOR_6 HOTEND_SENSOR_6
#define TEMP_SENSOR_7 HOTEND_SENSOR_7
#define TEMP_SENSOR_BED BED_SENSOR
#define TEMP_SENSOR_PROBE HOTEND_SENSOR_PROBE
#define TEMP_SENSOR_CHAMBER CHAMBER_SENSOR

#if (HOTEND_SENSOR_0 == -5 || HOTEND_SENSOR_1 == -5)
    #define MAX31865_SENSOR_OHMS HOTEND_MAX31865_SENSOR_OHMS
    #define MAX31865_CALIBRATION_OHMS HOTEND_MAX31865_CALIBRATION_OHMS
#endif

#if ENABLED(HOTEND_SENSOR_1_AS_REDUNDANT)
    #define TEMP_SENSOR_1_AS_REDUNDANT
#endif
#define MAX_REDUNDANT_TEMP_SENSOR_DIFF HOTEND_MAX_REDUNDANT_DIFF

#define TEMP_RESIDENCY_TIME HOTEND_TEMP_RESIDENCY_TIME
#define TEMP_WINDOW HOTEND_TEMP_WINDOW

#define TEMP_HYSTERESIS HOTEND_TEMP_HYSTERESIS

#define TEMP_BED_RESIDENCY_TIME BED_TEMP_RESIDENCY_TIME
#define TEMP_BED_WINDOW BED_TEMP_WINDOW

#define TEMP_BED_HYSTERESIS BED_TEMP_HYSTERESIS

#define HEATER_0_MINTEMP HOTEND_SENSOR_0_MINTEMP
#define HEATER_1_MINTEMP HOTEND_SENSOR_1_MINTEMP
#define HEATER_2_MINTEMP HOTEND_SENSOR_2_MINTEMP
#define HEATER_3_MINTEMP HOTEND_SENSOR_3_MINTEMP
#define HEATER_4_MINTEMP HOTEND_SENSOR_4_MINTEMP
#define HEATER_5_MINTEMP HOTEND_SENSOR_5_MINTEMP
#define HEATER_6_MINTEMP HOTEND_SENSOR_6_MINTEMP
#define HEATER_7_MINTEMP HOTEND_SENSOR_7_MINTEMP
#define BED_MINTEMP BED_SENSOR_MINTEMP

#define HEATER_0_MAXTEMP HOTEND_SENSOR_0_MAXTEMP
#define HEATER_1_MAXTEMP HOTEND_SENSOR_1_MAXTEMP
#define HEATER_2_MAXTEMP HOTEND_SENSOR_2_MAXTEMP
#define HEATER_3_MAXTEMP HOTEND_SENSOR_3_MAXTEMP
#define HEATER_4_MAXTEMP HOTEND_SENSOR_4_MAXTEMP
#define HEATER_5_MAXTEMP HOTEND_SENSOR_5_MAXTEMP
#define HEATER_6_MAXTEMP HOTEND_SENSOR_6_MAXTEMP
#define HEATER_7_MAXTEMP HOTEND_SENSOR_7_MAXTEMP
#define BED_MAXTEMP BED_SENSOR_MAXTEMP

#if ENABLED(HOTEND_PID)
    #define PIDTEMP
    #define PID_MAX HOTEND_PID_MAX
    #define PID_K1 HOTEND_PID_K1
    #if ENABLED(HOTEND_PID_EDIT_MENU)
        #define PID_EDIT_MENU
    #endif
    #if ENABLED(HOTEND_PID_AUTOTUNE_MENU)
        #define PID_AUTOTUNE_MENU
    #endif
    #if ENABLED(HOTEND_PID_PARAMS_PER_HOTEND)
        #define PID_PARAMS_PER_HOTEND
        #define DEFAULT_Kp_LIST HOTEND_PID_KP_LIST
        #define DEFAULT_Ki_LIST HOTEND_PID_KI_LIST
        #define DEFAULT_Kd_LIST HOTEND_PID_KD_LIST
    #else
        #define DEFAULT_Kp HOTEND_PID_KP
        #define DEFAULT_Ki HOTEND_PID_KI
        #define DEFAULT_Kd HOTEND_PID_KD
    #endif
#endif
#define BANG_MAX HOTEND_BANG_MAX

#if ENABLED(BED_PID)
    #define PIDBEDTEMP
    #if ENABLED(BED_PID_DEBUG)
        #define PID_BED_DEBUG
    #endif
    #define DEFAULT_bedKp BED_PID_KP
    #define DEFAULT_bedKi BED_PID_KI
    #define DEFAULT_bedKd BED_PID_KD
#endif

#define MAX_BED_POWER BED_MAX_POWER
#define MIN_BED_POWER BED_MIN_POWER

#if EITHER(HOTEND_PID, BED_PID)
    #if ENABLED(PRINTER_PID_DEBUG)
        #define PID_DEBUG
    #endif
    #if ENABLED(PRINTER_PID_OPENLOOP)
        #define PID_OPENLOOP
    #endif
    #if ENABLED(PRINTER_SLOW_PWM_HEATERS)
        #define SLOW_PWM_HEATERS
    #endif
    #define PID_FUNCTIONAL_RANGE PRINTER_PID_FUNCTIONAL_RANGE
#endif

#define PREHEAT_1_LABEL PRINTER_PREHEAT_1_LABEL   
#define PREHEAT_1_TEMP_HOTEND PRINTER_PREHEAT_1_TEMP_HOTEND
#define PREHEAT_1_TEMP_BED PRINTER_PREHEAT_1_TEMP_BED
#define PREHEAT_1_FAN_SPEED PRINTER_PREHEAT_1_FAN_SPEED

#define PREHEAT_2_LABEL PRINTER_PREHEAT_2_LABEL  
#define PREHEAT_2_TEMP_HOTEND PRINTER_PREHEAT_2_TEMP_HOTEND
#define PREHEAT_2_TEMP_BED PRINTER_PREHEAT_2_TEMP_BED  
#define PREHEAT_2_FAN_SPEED PRINTER_PREHEAT_2_FAN_SPEED   

/***********************************************************************/
// ┌─────────────────┐
// │ @section homing │
// ├─────────────────┤
// │                 │
// └─────────────────┘

#if ENABLED(AXIS_X_ENDSTOP_MIN)
    #define USE_XMIN_PLUG
#endif

#if ENABLED(AXIS_X_ENDSTOP_MAX)
    #define USE_XMAX_PLUG
#endif

#if ENABLED(AXIS_Y_ENDSTOP_MIN)
    #define USE_YMIN_PLUG
#endif

#if ENABLED(AXIS_Y_ENDSTOP_MAX)
    #define USE_YMAX_PLUG
#endif

#if ENABLED(AXIS_Z_ENDSTOP_MIN)
    #define USE_ZMIN_PLUG
#endif

#if ENABLED(AXIS_Z_ENDSTOP_MAX)
    #define USE_ZMAX_PLUG
#endif

#if ENABLED(PRINTER_ENDSTOP_PULLUP)
    #define ENDSTOPPULLUPS
#endif

#if DISABLED(PRINTER_ENDSTOP_PULLUP)
    #if ENABLED(AXIS_X_ENDSTOP_MAX_PULLUP)
        #define ENDSTOPPULLUPS_XMAX
    #endif
    #if ENABLED(AXIS_Y_ENDSTOP_MAX_PULLUP)
        #define ENDSTOPPULLUPS_YMAX
    #endif
    #if ENABLED(AXIS_Z_ENDSTOP_MAX_PULLUP)
        #define ENDSTOPPULLUPS_ZMAX
    #endif
    #if ENABLED(AXIS_X_ENDSTOP_MIN_PULLUP)
        #define ENDSTOPPULLUPS_XMIN
    #endif
    #if ENABLED(AXIS_Y_ENDSTOP_MIN_PULLUP)
        #define ENDSTOPPULLUPS_YMIN
    #endif
    #if ENABLED(AXIS_Z_ENDSTOP_MIN_PULLUP)
        #define ENDSTOPPULLUPS_ZMIN
    #endif
    #if ENABLED(AXIS_Z_ENDSTOP_MIN_PROBE_PULLUP)
        #define ENDSTOPPULLUPS_ZMIN_PROBE
    #endif
#endif

#if ENABLED(PRINTER_ENDSTOP_PULLDOWN)
    #define ENDSTOPPULLDOWNS
#endif

#if DISABLED(PRINTER_ENDSTOP_PULLDOWN)
    #if ENABLED(AXIS_X_ENDSTOP_MAX_PULLDOWN)
        #define ENDSTOPPULLDOWN_XMAX
    #endif
    #if ENABLED(AXIS_Y_ENDSTOP_MAX_PULLDOWN)
        #define ENDSTOPPULLDOWN_YMAX
    #endif
    #if ENABLED(AXIS_Z_ENDSTOP_MAX_PULLDOWN)
        #define ENDSTOPPULLDOWN_ZMAX
    #endif
    #if ENABLED(AXIS_X_ENDSTOP_MIN_PULLDOWN)
        #define ENDSTOPPULLDOWN_XMIN
    #endif
    #if ENABLED(AXIS_Y_ENDSTOP_MIN_PULLDOWN)
        #define ENDSTOPPULLDOWN_YMIN
    #endif
    #if ENABLED(AXIS_Z_ENDSTOP_MIN_PULLDOWN)
        #define ENDSTOPPULLDOWN_ZMIN
    #endif
    #if ENABLED(AXIS_Z_ENDSTOP_MIN_PROBE_PULLDOWN)
        #define ENDSTOPPULLDOWN_ZMIN_PROBE
    #endif
#endif

#define X_MIN_ENDSTOP_INVERTING AXIS_X_ENDSTOP_MIN_INVERTING
#define Y_MIN_ENDSTOP_INVERTING AXIS_Y_ENDSTOP_MIN_INVERTING
#define Z_MIN_ENDSTOP_INVERTING AXIS_Z_ENDSTOP_MIN_INVERTING
#define X_MAX_ENDSTOP_INVERTING AXIS_X_ENDSTOP_MAX_INVERTING
#define Y_MAX_ENDSTOP_INVERTING AXIS_Y_ENDSTOP_MAX_INVERTING
#define Z_MAX_ENDSTOP_INVERTING AXIS_Z_ENDSTOP_MAX_INVERTING
#define Z_MIN_PROBE_ENDSTOP_INVERTING AXIS_Z_ENDSTOP_MIN_PROBE_INVERTING

#define X_DRIVER_TYPE  AXIS_X_DRIVER
#define Y_DRIVER_TYPE  AXIS_Y_DRIVER
#define Z_DRIVER_TYPE  AXIS_Z_DRIVER
#define X2_DRIVER_TYPE AXIS_X2_DRIVER
#define Y2_DRIVER_TYPE AXIS_X2_DRIVER
#define Z2_DRIVER_TYPE AXIS_Z2_DRIVER
#define Z3_DRIVER_TYPE AXIS_Z3_DRIVER
#define Z4_DRIVER_TYPE AXIS_Z4_DRIVER
#define E0_DRIVER_TYPE AXIS_E0_DRIVER
#define E1_DRIVER_TYPE AXIS_E1_DRIVER
#define E2_DRIVER_TYPE AXIS_E2_DRIVER
#define E3_DRIVER_TYPE AXIS_E3_DRIVER
#define E4_DRIVER_TYPE AXIS_E4_DRIVER
#define E5_DRIVER_TYPE AXIS_E5_DRIVER
#define E6_DRIVER_TYPE AXIS_E6_DRIVER
#define E7_DRIVER_TYPE AXIS_E7_DRIVER

#if ENABLED(PRINTER_ENDSTOP_INTERRUPTS_FEATURE)
    #define ENDSTOP_INTERRUPTS_FEATURE
#endif

#if PRINTER_ENDSTOP_NOISE_THRESOLD > 0
    #define ENDSTOP_NOISE_THRESOLD PRINTER_ENDSTOP_NOISE_THRESOLD
#endif

#if ENABLED(PRINTER_DETECT_BROKEN_ENDSTOP)
    #define DETECT_BROKEN_ENDSTOP
#endif

#if ENABLED(MOTION_DISABLE_BEFORE_HOMING)
    #define NO_MOTION_BEFORE_HOMING
#endif

#if ENABLED(AXIS_Z_UNKNOWN_NO_RAISE)
    #define UNKNOWN_Z_NO_RAISE
#endif

#if AXIS_Z_HOMING_HEIGHT > 0
    #define Z_HOMING_HEIGHT AXIS_Z_HOMING_HEIGHT
#endif

#if AXIS_Z_AFTER_HOMING > 0
    #define Z_AFTER_HOMING AXIS_Z_AFTER_HOMING
#endif

#define X_HOME_DIR AXIS_X_HOME_DIR
#define Y_HOME_DIR AXIS_Y_HOME_DIR
#define Z_HOME_DIR AXIS_Z_HOME_DIR

#if ENABLED(BED_CENTER_AT_ORIGIN)
    #define BED_CENTER_AT_0_0
#endif

#if AXIS_X_MANUAL_HOME_POS != 0
    #define MANUAL_X_HOME_POS AXIS_X_MANUAL_HOME_POS
#endif

#if AXIS_Y_MANUAL_HOME_POS != 0
    #define MANUAL_Y_HOME_POS AXIS_Y_MANUAL_HOME_POS
#endif

#if AXIS_Z_MANUAL_HOME_POS != 0
    #define MANUAL_Z_HOME_POS AXIS_Z_MANUAL_HOME_POS
#endif

#if ENABLED(AXIS_Z_SAFE_HOMING)
    #define Z_SAFE_HOMING
    #define Z_SAFE_HOMING_X_POINT AXIS_Z_SAFE_HOMING_X_POINT 
    #define Z_SAFE_HOMING_Y_POINT AXIS_Z_SAFE_HOMING_Y_POINT
#endif

#define HOMING_FEEDRATE_XY MOTION_HOMING_FEEDRATE_XY
#define HOMING_FEEDRATE_Z  MOTION_HOMING_FEEDRATE_Z

#if ENABLED(MOTION_VALIDATE_HOMING_ENDSTOPS)
    #define VALIDATE_HOMING_ENDSTOPS
#endif

/***********************************************************************/
// ┌─────────────────┐
// │ @section motion │
// ├─────────────────┤
// │                 │
// └─────────────────┘

#if ENABLED(MOTION_DISTINCT_E_FACTORS)
    #define DISTINCT_E_FACTORS
    #define ALL_E_STEPS_MM AXIS_VALUE_LIST(EXTRUDER_NUMBERS,E,STEPS_MM)
    #define ALL_E_MAX_FEEDRATE AXIS_VALUE_LIST(EXTRUDER_NUMBERS,E,MAX_FEEDRATE)
    #define ALL_E_MAX_ACCELERATION AXIS_VALUE_LIST(EXTRUDER_NUMBERS,E,MAX_ACCELERATION)
#else
    #define ALL_E_STEPS_MM AXIS_E0_STEPS_MM
    #define ALL_E_MAX_FEEDRATE AXIS_E0_MAX_FEEDRATE
    #define ALL_E_MAX_ACCELERATION AXIS_E0_MAX_ACCELERATION
#endif

#define DEFAULT_AXIS_STEPS_PER_UNIT { AXIS_X_STEPS_MM, AXIS_Y_STEPS_MM, AXIS_Z_STEPS_MM, ALL_E_STEPS_MM }

#define DEFAULT_MAX_FEEDRATE { AXIS_X_MAX_FEEDRATE, AXIS_Y_MAX_FEEDRATE, AXIS_Z_MAX_FEEDRATE, ALL_E_MAX_FEEDRATE }

#if ENABLED(MOTION_LIMITED_MAX_FEEDRATE_EDITING)
    #define LIMITED_MAX_FR_EDITING
    #define MAX_FEEDRATE_EDIT_VALUES { AXIS_X_MAX_FEEDRATE_EDIT_VALUE, AXIS_Y_MAX_FEEDRATE_EDIT_VALUE, AXIS_Z_MAX_FEEDRATE_EDIT_VALUE, AXIS_E0_MAX_FEEDRATE_EDIT_VALUE }
#endif

#define DEFAULT_MAX_ACCELERATION { AXIS_X_MAX_ACCELERATION, AXIS_Y_MAX_ACCELERATION, AXIS_Z_MAX_ACCELERATION, ALL_E_MAX_ACCELERATION }

#if ENABLED(MOTION_LIMITED_MAX_ACCELERATION_EDITING)
    #define LIMITED_MAX_ACCEL_EDITING
    #define MAX_ACCEL_EDIT_VALUES { AXIS_X_MAX_ACCELERATION_EDIT_VALUE, AXIS_Y_MAX_FEEDRATE_EDIT_VALUE, AXIS_Z_MAX_ACCELERATION_EDIT_VALUE, AXIS_E0_MAX_ACCELERATION_EDIT_VALUE }
#endif

#define DEFAULT_ACCELERATION MOTION_DEFAULT_ACCELERATION
#define DEFAULT_RETRACT_ACCELERATION MOTION_DEFAULT_RETRACT_ACCELERATION
#define DEFAULT_TRAVEL_ACCELERATION MOTION_DEFAULT_TRAVEL_ACCELERATION

#if ENABLED(MOTION_CLASSIC_JERK)
    #define CLASSIC_JERK
    #define DEAFULT_XJERK AXIS_X_JERK
    #define DEFAULT_YJERK AXIS_Y_JERK
    #define DEFAULT_ZJERK AXIS_Z_JERK

    #define TRAVEL_EXTRA_XYJERK MOTION_TRAVEL_EXTRA_XYJERK

    #if ENABLED(MOTION_LIMITED_JERK_EDITING)
        #define MAX_JERK_EDIT_VALUES { AXIS_X_JERK_EDIT_VALUE , AXIS_Y_JERK_EDIT_VALUE, AXIS_Z_JERK_EDIT_VALUE, AXIS_E0_JERK_EDIT_VALUE }
    #endif
#endif

#define DEFAULT_EJERK AXIS_E0_JERK

#if DISABLED(MOTION_CLASSIC_JERK)
    #define JUNCTION_DEVIATION_MM MOTION_JUNCTION_DEVIATION
    #if ENABLED(MOTION_JD_HANDLE_SMALL_SEGMENTS)
        #define JD_HANDLE_SMALL_SEGMENTS
    #endif
#endif

#if ENABLED(MOTION_S_CURVE_ACCELERATION)
    #define S_CURVE_ACCELERATION
#endif

#define X_ENABLE_ON AXIS_X_ENABLE_ON
#define Y_ENABLE_ON AXIS_Y_ENABLE_ON
#define Z_ENABLE_ON AXIS_Z_ENABLE_ON
#define E_ENABLE_ON AXIS_E0_ENABLE_ON

#define DISABLE_X AXIS_X_DISABLE
#define DISABLE_Y AXIS_Y_DISABLE
#define DISABLE_Z AXIS_Z_DISABLE

/***********************************************************************/
// ┌─────────────────┐
// │ @section probes │
// ├─────────────────┤
// │                 │
// └─────────────────┘

#if ENABLED(PROBE_USES_Z_ENDSTOP_MIN_PIN)
    #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#endif

#if ENABLED(PROBE_USES_FOR_Z_HOMING)
    #define USE_PROBE_FOR_Z_HOMING
#endif

#if PROBE_PIN > 0
    #define Z_MIN_PROBE_PIN PROBE_PIN
#endif

#define NOZZLE_TO_PROBE_OFFSET { PROBE_X_OFFSET, PROBE_Y_OFFSET, PROBE_Z_OFFSET }
#define PROBING_MARGIN PROBE_MARGIN

#define XY_PROBE_SPEED PROBE_SPEED
#define Z_PROBE_SPEED_FAST PROBE_Z_SPEED_FAST
#define Z_PROBE_SPEED_SLOW PROBE_Z_SPEED_SLOW

#if PROBE_MULTIPLE_PROBING > 0
    #define MULTIPLE_PROBING PROBE_MULTIPLE_PROBING
#endif

#if PROBE_EXTRA_PROBING > 0
    #define EXTRA_PROBING PROBE_EXTRA_PROBING
#endif

#define Z_CLEARANCE_DEPLOY_PROBE PROBE_Z_CLEARANCE_DEPLOY
#define Z_CLEARANCE_BETWEEN_PROBES PROBE_Z_CLEARANCE_BETWEEN_PROBES
#define Z_CLEARANCE_MULTI_PROBE PROBE_Z_CLEARANCE_MULTI_PROBE

#if PROBE_Z_AFTER_PROBING > 0
    #define Z_AFTER_PROBING PROBE_Z_AFTER_PROBING
#endif

#define Z_PROBE_LOW_POINT PROBE_Z_LOW_POINT

#define Z_PROBE_OFFSET_RANGE_MIN PROBE_Z_OFFSET_RANGE_MIN
#define Z_PROBE_OFFSET_RANGE_MAX PROBE_Z_OFFSET_RANGE_MAX

#if ENABLED(PROBE_REPEATABILITY_TEST)
    #define Z_MIN_PROBE_REPEATABILITY_TEST
#endif

#if ENABLED(PROBE_PAUSE_BEFORE_DEPLOY_STOW)
    #define PAUSE_BEFORE_DEPLOY_STOW
    #if ENABLED(PROBE_PAUSE_DEPLOY_WHEN_TRIGGERED)
        #define PAUSE_PROBE_DEPLOY_WHEN_TRIGGERED
    #endif
#endif

#if ENABLED(PROBE_HEATERS_OFF)
    #define PROBING_HEATERS_OFF 
    #if ENABLED(PROBE_WAIT_FOR_BED_HEATER)
        #define WAIT_FOR_BED_HEATER 
    #endif
#endif

#if ENABLED(PROBE_FANS_OFF)
    #define PROBING_FANS_OFF  
#endif

#if ENABLED(PROBE_STEPPERS_OFF)
    #define PROBING_STEPPERS_OFF  
#endif

#if PROBE_DELAY_BEFORE_PROBING > 0
    #define DELAY_BEFORE_PROBING PROBE_DELAY_BEFORE_PROBING
#endif

/***********************************************************************/
// ┌────────────────────┐
// │ @section calibrate │
// ├────────────────────┤
// │                    │
// └────────────────────┘

#if PRINTER_HAS(LEVELING,point3)
    #define AUTO_BED_LEVELING_3POINT
#endif

#if PRINTER_HAS(LEVELING,linear)
    #define AUTO_BED_LEVELING_LINEAR
#endif

#if PRINTER_HAS(LEVELING,bilinear)
    #define AUTO_BED_LEVELING_BILINEAR
#endif

#if PRINTER_HAS(LEVELING,ubl)
    #define AUTO_BED_LEVELING_UBL
#endif

#if PRINTER_HAS(LEVELING,mesh)
    #define MESH_BED_LEVELING
#endif

#if ENABLED(LEVELING_RESTORE_AFTER_G28)
    #define RESTORE_LEVELING_AFTER_G28
#endif

#if ENABLED(LEVELING_DEBUG)
    #define DEBUG_LEVELING_FEATURE
#endif

#if ANY(LEVELING_MESH_ENABLED,LEVELING_BILINEAR_ENABLED,LEVELING_UBL_ENABLED)

    #if ENABLED(LEVELING_FADE_HEIGHT)
        #define ENABLE_LEVELING_FADE_HEIGHT
    #endif

    #if ENABLED(LEVELING_SEGMENT_LEVELED_MOVES)
        #define SEGMENT_LEVELED_MOVES
    #endif
    #define LEVELED_SEGMENT_LENGTH LEVELING_LEVELED_SEGMENT_LENGTH

    #if ENABLED(LEVELING_G26_MESH_VALIDATION)
        #define G26_MESH_VALIDATION
        #define MESH_TEST_NOZZLE_SIZE LEVELING_MESH_TEST_NOZZLE_SIZE    
        #define MESH_TEST_LAYER_HEIGHT LEVELING_MESH_TEST_LAYER_HEIGHT
        #define MESH_TEST_HOTEND_TEMP LEVELING_MESH_TEST_HOTEND_TEMP
        #define MESH_TEST_BED_TEMP LEVELING_MESH_TEST_BED_TEMP    
        #define G26_XY_FEEDRATE LEVELING_G26_XY_FEEDRATE       
        #define G26_RETRACT_MULTIPLIER LEVELING_G26_RETRACT_MULTIPLIER
    #endif

#endif

#if EITHER(LEVELING_LINEAR_ENABLED, LEVELING_BILINEAR_ENABLED)

    #define GRID_MAX_POINTS_X LEVELING_GRID_MAX_POINTS_X
    #define GRID_MAX_POINTS_Y LEVELING_GRID_MAX_POINTS_Y

    #if ENABLED(LEVELING_PROBE_Y_FIRST)
        #define PROBE_Y_FIRST
    #endif
  
    #if ENABLED(LEVELING_BILINEAR_ENABLED)

        #if ENABLED(LEVELING_EXTRAPOLATE_BEYOND_GRID)
            #define EXTRAPOLATE_BEYOND_GRID
        #endif

        #if ENABLED(LEVELING_ABL_BILINEAR_SUBDIVISION)
            #define ABL_BILINEAR_SUBDIVISION
            #define BILINEAR_SUBDIVISIONS LEVELING_BILINEAR_SUBDIVISIONS
        #endif
    #endif

#elif ENABLED(LEVELING_UBL_ENABLED)
    #if ENABLED(LEVELING_MESH_EDIT_GFX_OVERLAY )
        #define MESH_EDIT_GFX_OVERLAY  
    #endif

    #define MESH_INSET LEVELING_MESH_INSET             
    #define GRID_MAX_POINTS_X LEVELING_GRID_MAX_POINTS_X    
    #define GRID_MAX_POINTS_Y LEVELING_GRID_MAX_POINTS_Y

    #if ENABLED(LEVELING_UBL_MESH_EDIT_MOVES_Z)
        #define UBL_MESH_EDIT_MOVES_Z 
    #endif

    #if ENABLED(LEVELING_UBL_SAVE_ACTIVE_ON_M500)
        #define UBL_SAVE_ACTIVE_ON_M500
    #endif
       
    #if LEVELING_UBL_Z_RAISE_WHEN_OFF_MESH > 0
        #define UBL_Z_RAISE_WHEN_OFF_MESH LEVELING_UBL_Z_RAISE_WHEN_OFF_MESH
    #endif

#elif ENABLED(LEVELING_MESH_ENABLED)

    #define MESH_INSET LEVELING_MESH_INSET         
    #define GRID_MAX_POINTS_X LEVELING_GRID_MAX_POINTS_X     
    #define GRID_MAX_POINTS_Y LEVELING_GRID_MAX_POINTS_Y

    #if ENABLED(LEVELING_MESH_G28_REST_ORIGIN)
        #define MESH_G28_REST_ORIGIN 
    #endif

#endif 

#if ENABLED(LEVELING_FROM_LCD)

    #define LCD_BED_LEVELING
    #define MESH_EDIT_Z_STEP LEVELING_MESH_EDIT_Z_STEP
    #define LCD_PROBE_Z_RANGE LEVELING_LCD_PROBE_Z_RANGE

    #if ENABLED(LEVELING_MESH_EDIT_MENU)
        #define MESH_EDIT_MENU 
    #endif    

#endif

#if ENABLED(LEVELING_BED_CORNERS)
    
    #define LEVEL_BED_CORNERS
    #define LEVEL_CORNERS_INSET_LFRB LEVELING_CORNERS_INSET_LFRB
    #define LEVEL_CORNERS_HEIGHT LEVELING_CORNERS_HEIGHT
    #define LEVEL_CORNERS_Z_HOP LEVELING_CORNERS_Z_HOP

    #if ENABLED(LEVELING_CENTER_TOO)
        #define LEVEL_CENTER_TOO 
    #endif
      
#endif

#ifdef LEVELING_Z_PROBE_END_SCRIPT
    #define Z_PROBE_END_SCRIPT LEVELING_Z_PROBE_END_SCRIPT
#endif

//TODO BED SKEW



/***********************************************************************/
// ┌──────────────┐
// │ @section lcd │
// ├──────────────┤
// │              │
// └──────────────┘



/***********************************************************************/
// ┌─────────────────┐
// │ @section extras │
// ├─────────────────┤
// │                 │
// └─────────────────┘

